
(()=>{
const DATA=window.TRIP_DATA; const ROUTES=Object.keys(DATA.routes);
const GEOMETRY=window.TRIP_ROUTE_GEOMETRY||{};
const I18N=window.TRIP_I18N||{ko_to_en:{},en_to_ko:{},places:{}};
const FRESHNESS=window.TRIP_FRESHNESS||{default_status:'RECHECK_REQUIRED',records:[]};
const RUNTIME_CONTRACT=window.TRIP_RUNTIME_CONTRACT||{};
const STORAGE_KEY='trip_visualizer_runtime_v1';
const stored=(key,fallback)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const restored=(()=>{try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return value?.version===1?value:{}}catch{return {}}})();
const restoredRoutes=Array.isArray(restored.routes)?restored.routes.filter(r=>ROUTES.includes(r)):[...ROUTES];
const restoredDates=new Set(['all',...DATA.dates.map(x=>x.key)]),restoredRegions=new Set(Object.keys(DATA.region_cfg));
const state={routes:new Set(restoredRoutes.length?restoredRoutes:ROUTES),provider:'vector',region:restoredRegions.has(restored.region)?restored.region:'overall',date:restoredDates.has(restored.date)?restored.date:'all',selected:typeof restored.selected==='string'?restored.selected:null,tab:['timeline','details'].includes(restored.tab)?restored.tab:'timeline',lang:['ko','en'].includes(restored.lang)?restored.lang:stored('trip_lang','ko'),theme:['light','dark'].includes(restored.theme)?restored.theme:stored('trip_theme','light'),providerIdentity:RUNTIME_CONTRACT.providers?.vector?.identity||'smart-local-vector',providerHealth:{vector:'loading',satellite:'untested'},providerEvents:[],localAssets:{status:'checking',failures:[],pending:0,completed:0,failed:0,resources:[]},appReady:false,mapVisualReady:false,loadingStatus:'loading',touch:false,panelWidth:Number(restored.panelWidth||stored('trip_panel_width','390')),mobilePanelHeight:Number(restored.mobilePanelHeight||stored('trip_mobile_panel_height','48')),panelHidden:!!restored.panelHidden,runtime:{sequence:0,probeSequence:0,mapCreations:0,mapRemovals:0,drawRequests:0,providerSwitches:0,events:[]},providerStats:{vector:{healthProbes:0,viewportProbes:0,tileErrors:0,fallbacks:0},satellite:{healthProbes:0,viewportProbes:0,tileErrors:0,fallbacks:0}}};
const routeMeta=DATA.routes; const markerByKey=Object.fromEntries(DATA.markers.map(x=>[x.place_key,x]));
let photoMarkers=new Map(),clusterMarkers=[],legMarkers=[],photoMap=null,drawQueue=Promise.resolve(),vectorUrl='assets/vector/sf_trip.pmtiles',renderedProvider=null,renderedTheme=null,previewReturnTarget=null,mapFocusReturnTarget=null,routeExplainReturnTarget=null,panelReturnFocus=null,suppressMarkerPreviewFocus=false,suppressRouteInfoFocus=false;
const UI={ko:{subtitle:'여행 시각화',routes:'경로',date:'날짜',region:'지역',map:'지도',allDates:'전체 날짜',overall:'전체',sf:'SF + 마린',monterey:'몬터레이',yosemite:'요세미티',vector:'스마트 지도',satellite:'위성 + 라벨',timeline:'일정',details:'상세',compare:'경로 전략 비교',whyNow:'왜 지금?',advantage:'장점',decision:'판단·변경 규칙',summary:'장소 요약',experience:'현장 경험',exactTiming:'경로별 정확한 시간',directions:'Google 지도에서 보기',shared:'공통',specific:'경로 전용',plan:'계획·회복',photoStop:'사진 장소',routeMode:'이동 방식',noMapped:'지도 좌표가 없는 일정',stops:'장소',days:'일정일',next:'지도에서 일정 선택',explore:'장소 보기',conceptual:'경로 의미',providerReady:'로컬 스마트 지도 준비 완료',providerFallback:'위성 타일 실패 → 스마트 지도로 전환',liveReady:'실시간 지도 준비 완료',selectStop:'장소를 선택하세요',browseHint:'현재 필터의 사진 장소를 보거나 지도 마커를 누르세요.',close:'닫기',dark:'다크',lightTheme:'라이트',language:'언어',allRoutes:'전체 경로',noSlots:'현재 필터에 맞는 일정이 없습니다.',replan:'변경 규칙',time:'시간',whyPlace:'이 장소를 선택한 이유',freshness:'변경 가능 정보: 출발 전 공식 소스 재확인 필요'},en:{subtitle:'Trip visualizer',routes:'Routes',date:'Date',region:'Region',map:'Map',allDates:'All dates',overall:'Overall',sf:'SF + Marin',monterey:'Monterey',yosemite:'Yosemite',vector:'Smart map',satellite:'Satellite + labels',timeline:'Timeline',details:'Details',compare:'Compare route strategies',whyNow:'Why now?',advantage:'Advantage',decision:'Decision / replan rules',summary:'Place summary',experience:'What you will experience',exactTiming:'Exact timing by route',directions:'Open Google Maps',shared:'Shared',specific:'Route-specific',plan:'Plan / recovery',photoStop:'Photo stop',routeMode:'Travel mode',noMapped:'Schedule item without a map coordinate',stops:'stops',days:'days',next:'Choose a day on the map',explore:'Explore stops',conceptual:'Route meaning',providerReady:'Local Smart map ready',providerFallback:'Satellite tiles failed → Smart map',liveReady:'Live map ready',selectStop:'Choose a place',browseHint:'Browse the photo stops in this filter, or tap a marker on the map.',close:'Close',dark:'Dark',lightTheme:'Light',language:'Language',allRoutes:'All routes',noSlots:'No itinerary slots match these filters.',replan:'Decision rule',time:'Time',whyPlace:'Why this place',freshness:'Changeable facts: recheck official sources before departure'}};
Object.assign(UI.ko,{subtitle:`${ROUTES.length}개 경로 · ${DATA.dates.length}일 일정 · 실제 사진 ${DATA.markers.length*3}장 · 검증된 ${DATA.markers.length}개 장소`,conceptual:'색 선 = 실제 경로 · 긴 점선 = 회복 간격 · 짧은 점선 = 택1/조건부',providerReady:'로컬 스마트 지도 고정 · 외부 지도 요청 없음',providerFallback:'위성 타일 실패 → 스마트 지도로 자동 전환',must:'필수',strong:'강력',swap:'택1 대체',bonus:'보너스',conditional:'조건부',recovery:'회복 간격',choice:'택1 연결',main:'기본',auditAdded:'공식 소스 교차검증 추가',choiceWarning:'같은 선택 그룹은 하나만 실행'});
Object.assign(UI.en,{subtitle:`${ROUTES.length} routes · ${DATA.dates.length} days · ${DATA.markers.length*3} real photos · ${DATA.markers.length} verified places`,conceptual:'Colored lines = routes · long dash = recovery gap · short dash = choice/conditional',providerReady:'Local Smart map locked · no external map requests',providerFallback:'Satellite tiles failed → Smart map automatically',must:'Must',strong:'Strong',swap:'Choose-one swap',bonus:'Bonus',conditional:'Conditional',recovery:'Recovery gap',choice:'Choose-one link',main:'Main',auditAdded:'Added by official-source audit',choiceWarning:'Run only one stop in the same choice group'});
Object.assign(UI.ko,{bestFor:'이 경로가 맞는 경우',tradeoff:'감수할 것',routeRule:'선택·전환 규칙',regretGuard:'후회 방지',routeScore:'경로 점수',explainRoute:'경로 설명',showPanel:'패널 열기',hidePanel:'패널 닫기',smallerPanel:'패널 작게',largerPanel:'패널 크게',resizePanel:'일정 패널 크기 조절'});
Object.assign(UI.en,{bestFor:'Best for',tradeoff:'Trade-off',routeRule:'Choose / switch rule',regretGuard:'Regret guard',routeScore:'Route score',explainRoute:'Explain route',showPanel:'Show panel',hidePanel:'Hide panel',smallerPanel:'Smaller panel',largerPanel:'Larger panel',resizePanel:'Resize itinerary panel'});
Object.assign(UI.ko,{tripOverview:'가족 여행 의사결정 지도',fieldSummary:'공통 골격을 먼저 보고, 경로별 선택·전환은 필요할 때 비교하세요.',branchLegend:'기본 · 필수  |  조건부 · 상황에 따라  |  택1 대체 · 하나만  |  보너스 · 여유 시  |  회복 간격 · 이동이 아닌 휴식',retryLocal:'스마트 지도 다시 시도',providerFailure:'위성 연결 실패. 계획은 유지되며 로컬 스마트 지도를 사용합니다.'});
Object.assign(UI.en,{tripOverview:'Family-trip decision map',fieldSummary:'Start with the shared backbone, then compare route-specific choices and switches when needed.',branchLegend:'Main / must-do  |  Conditional / if fit  |  Swap / choose one  |  Bonus / if energy remains  |  Recovery / rest gap',retryLocal:'Retry Smart map',providerFailure:'Satellite connection failed. Your plan is preserved and the local Smart map remains active.'});
const u=key=>UI[state.lang]?.[key]||UI.en[key]||DATA.region_cfg?.[key]?.[state.lang==='ko'?'label_ko':'label']||DATA.providers?.[key]?.label||key;
const tr=value=>{const s=String(value??'');return state.lang==='en'?(I18N.ko_to_en[s]||s):(I18N.en_to_ko[s]||s)};
const modeLabel=mode=>({ko:{drive:'차량',walk:'도보',ferry:'페리'},en:{drive:'Drive',walk:'Walk',ferry:'Ferry'}})[state.lang]?.[mode]||mode;
const tierLabel=tier=>u(tier||'strong');
const tierFor=x=>x?.schedule_tier||(String(x?.role||'').includes('필수')?'must':String(x?.role||'').includes('근처')?'bonus':'strong');
const scoreLabel=key=>state.lang==='ko'?key:({'군중차익':'Crowd edge','아기편안':'Infant comfort','기상옵션':'Weather options','동선효율':'Route efficiency','후회방지':'Regret protection','사진/빛':'Photo / light','후반체력':'Late-trip energy'}[key]||key);
const decisionLabel=key=>({ko:{baby_nap_delay_45min:'낮잠이 45분 이상 밀리면',family_energy_below_6:'가족 에너지가 6/10 미만이면',glacier_bad:'Glacier Point 날씨가 나쁘면',battery_parking:'Battery Spencer 주차가 어렵다면',twin_peaks_visibility:'Twin Peaks 시야가 나쁘면'},en:{baby_nap_delay_45min:'Baby nap delayed 45+ minutes',family_energy_below_6:'Family energy below 6/10',glacier_bad:'Poor Glacier Point weather',battery_parking:'Battery Spencer parking trouble',twin_peaks_visibility:'Poor Twin Peaks visibility'}})[state.lang]?.[key]||key.replaceAll('_',' ');
const placeName=k=>I18N.places[k]?.[0]||markerByKey[k]?.name||k;
const placeKo=k=>I18N.places[k]?.[1]||'';
const timelineTitle=t=>t.spatial_keys?.length===1?placeName(t.spatial_keys[0]):tr(t.title);
const dateLabel=s=>{const key=String(s||'').match(/^\d+\/\d+/)?.[0];if(!key)return tr(s);const meta=DATA.dates.find(d=>d.key===key);return state.lang==='en'?(meta?.label_en||key):(meta?.label||key)};
const routeNarrative=r=>routeMeta[r]?.explanation?.[state.lang]||{best_for:tr(routeMeta[r]?.subtitle||''),tradeoff:tr(routeMeta[r]?.core_reason||''),decision_rule:tr(routeMeta[r]?.core_reason||''),regret_guard:tr(routeMeta[r]?.core_reason||'')};
function persistState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,routes:[...state.routes].sort(),region:state.region,date:state.date,selected:state.selected,tab:state.tab,lang:state.lang,theme:state.theme,panelWidth:Math.round(state.panelWidth),mobilePanelHeight:Math.round(state.mobilePanelHeight),panelHidden:state.panelHidden}))}catch{}}
function recordRuntimeEvent(type,provider,detail={}){const event={seq:++state.runtime.sequence,type,provider,...detail};state.providerEvents.push(event);state.runtime.events.push(event);if(state.providerEvents.length>80)state.providerEvents.shift();if(state.runtime.events.length>80)state.runtime.events.shift();}
function mapFailureText(error,phase='runtime'){const detail=String(error?.message||error||'local asset failure');return state.lang==='ko'?`로컬 스마트 지도 오류 (${phase}): ${detail}. 원격 지도로 대체하지 않았습니다.`:`Local Smart map failure (${phase}): ${detail}. No remote provider was substituted.`}
function showMapFailure(error,phase='runtime'){const message=mapFailureText(error,phase),el=document.getElementById('mapError');if(el){el.innerHTML=`<span class="map-error-message">${esc(message)}</span><button type="button" id="mapRetry">${u('retryLocal')}</button>`;el.hidden=false;el.querySelector('#mapRetry').onclick=()=>window.location.reload()}const screen=document.getElementById('loadingScreen');if(screen){screen.classList.add('failed');screen.setAttribute('aria-hidden','false')}state.appReady=false;state.mapVisualReady=false;state.loadingStatus='failed';setLoading(message);state.provider='vector';state.providerHealth.vector='failed';state.localAssets.status='failed';if(!state.localAssets.failures.includes(message))state.localAssets.failures.push(message);recordRuntimeEvent('smart_failure','vector',{phase,message});renderProviderState?.();persistState();}
function localMapError(event){const source=String(event?.sourceId||'');const message=String(event?.error?.message||event?.message||event?.error||'');return source==='basemap'||source==='hillshade'||/pmtiles|tripasset|glyph|sprite|font|local asset|range|byte serving/i.test(message);}
async function setupVector(){if(!window.TRIP_VECTOR)throw new Error('Local vector renderer missing');const {Protocol,PMTiles,FileSource}=window.TRIP_VECTOR,protocol=new Protocol();let archive;if(window.EMBEDDED_VECTOR){if(typeof window.EMBEDDED_VECTOR!=='string'||window.EMBEDDED_VECTOR.length<100000)throw new Error('Embedded PMTiles payload is missing or truncated');const response=await fetch('data:application/octet-stream;base64,'+window.EMBEDDED_VECTOR);if(!response.ok)throw new Error('Embedded PMTiles payload could not be decoded');const blob=await response.blob();if(blob.size<127)throw new Error('Embedded PMTiles payload is too small');const file=new File([blob],'sf_trip.pmtiles');vectorUrl='sf_trip.pmtiles';archive=new PMTiles(new FileSource(file));}else archive=new PMTiles(vectorUrl);const header=await archive.getHeader();if(!header||![1,6].includes(header.tileType)||header.maxZoom<1||header.minLon>=header.maxLon||header.minLat>=header.maxLat)throw new Error('Smart map PMTiles header is invalid');protocol.add(archive);maplibregl.addProtocol('pmtiles',protocol.tile);maplibregl.addProtocol('tripasset',async params=>{const path=decodeURIComponent(params.url.replace('tripasset://',''));const embedded=window.EMBEDDED_MAP_ASSETS?.[path],entry={path,status:'pending',started:performance.now()};state.localAssets.pending++;state.localAssets.resources.push(entry);try{const response=await fetch(embedded?'data:application/octet-stream;base64,'+embedded:path);if(!response.ok)throw new Error('Missing map asset '+path);const data=path.endsWith('.json')?await response.json():await response.arrayBuffer();entry.status='ready';entry.completed=performance.now();state.localAssets.completed++;return {data};}catch(error){entry.status='failed';entry.error=String(error?.message||error);state.localAssets.failed++;throw error;}finally{state.localAssets.pending=Math.max(0,state.localAssets.pending-1);}});state.localAssets.status='ready';state.providerHealth.vector='ready';recordRuntimeEvent('smart_ready','vector',{identity:state.providerIdentity});}
const photoPath=(key,role,variant)=>`assets/photos/${variant}/${key}__${role}.webp`;
const photoSrc=path=>window.EMBEDDED_PHOTOS?.[path]||path;
function bindLocalImageFailures(root){root?.querySelectorAll('img').forEach(img=>{if(!img.src.startsWith('data:'))img.addEventListener('error',()=>showMapFailure(new Error(`Missing local photo ${img.getAttribute('src')||''}`),'photo_asset'));});}
const isMobile=()=>window.matchMedia('(max-width:800px)').matches;
function routeIntersects(arr){return (arr||[]).some(r=>state.routes.has(r));}
function dateMatchesOccurrence(o){return state.date==='all'||(o.date||'').startsWith(state.date+' ' )||(o.date||'')===state.date;}
function markerVisible(m){if(!routeIntersects(m.routes))return false;if(state.region!=='overall'&&DATA.place_region[m.place_key]!==state.region)return false;if(state.date==='all')return true;return m.occurrences.some(o=>state.routes.has(o.route)&&dateMatchesOccurrence(o));}
function timelineVisible(t){if(!routeIntersects(t.routes))return false;if(state.date!=='all'&&t.date_key!==state.date)return false;if(state.region==='overall')return true;return t.regions.includes(state.region);}
function legVisible(l){if(!routeIntersects(l.routes))return false;if(state.date!=='all'&&l.date!==state.date)return false;const from=markerByKey[l.from],to=markerByKey[l.to];if(from&&to&&!l.routes.some(r=>state.routes.has(r)&&from.occurrences.some(o=>o.route===r&&o.date.startsWith(l.date))&&to.occurrences.some(o=>o.route===r&&o.date.startsWith(l.date))))return false;if(state.region!=='overall'){
  const fr=DATA.place_region[l.from], tr=DATA.place_region[l.to]; if(fr!==state.region&&tr!==state.region)return false;
  if(l.render_style==='transfer_dots')return false;
}return true;}
function vectorStyle({labelsOnly=false}={}){
  const v=window.TRIP_VECTOR,dark=state.theme==='dark',layers=v.layers('basemap',v.namedFlavor(dark?'dark':'light'),{lang:'en',labelsOnly});
  for(const layer of layers){
    if(layer.type==='background')layer.paint['background-color']=dark?'#334553':'#f3f0e9';
    if(dark&&!labelsOnly){
      if(layer.id==='earth')layer.paint['fill-color']='#334553';
      if(layer.id==='landcover')layer.paint['fill-color']=['match',['get','kind'],'grassland','#365a49','urban_area','#344553','barren','#4b4a45','farmland','#415847','glacier','#637584','scrub','#3a5146','#2b473e'];
      if(layer.id==='landuse_park'||layer.id==='landuse_urban_green')layer.paint['fill-color']='#315847';
      if(layer.id==='water')layer.paint['fill-color']='#28566e';
      if(layer.id.startsWith('water_')&&layer.type==='line')layer.paint['line-color']='#3b7892';
      if(layer.id==='buildings')layer.paint['fill-color']='#263745';
      if(layer.id.startsWith('roads_')&&layer.type==='line'){const casing=layer.id.includes('casing'),major=/highway|major|link/.test(layer.id);layer.paint['line-color']=casing?'#223645':major?'#91aabd':'#607b8e';}
      if(layer.type==='symbol'&&layer.paint?.['text-color']){layer.paint['text-color']=layer.id.startsWith('places_')?'#edf5fb':'#d3e2ec';layer.paint['text-halo-color']='#253949';layer.paint['text-halo-width']=1.25;}
    }
    if(labelsOnly){if(layer.paint?.['text-color'])layer.paint['text-color']='#fff';if(layer.paint?.['text-halo-color'])layer.paint['text-halo-color']='#202a36';if(layer.paint?.['text-halo-width'])layer.paint['text-halo-width']=2.2;}
  }
  const sources={basemap:{type:'vector',url:'pmtiles://'+vectorUrl,attribution:'© OpenStreetMap contributors · Protomaps'}};
  if(!labelsOnly){sources.hillshade={type:'image',url:window.EMBEDDED_HILLSHADE||'assets/vector/yosemite_hillshade_shadow.webp',coordinates:[[-119.99,37.95],[-119.35,37.95],[-119.35,37.38],[-119.99,37.38]]};const index=layers.findIndex(layer=>layer.id==='roads_tunnels_other_casing');layers.splice(index<0?layers.length:index,0,{id:'yosemite-relief',type:'raster',source:'hillshade',minzoom:8,maxzoom:18,paint:{'raster-opacity':dark?.58:.72,'raster-fade-duration':0}});}
  return {version:8,glyphs:'tripasset://assets/vector/fonts/{fontstack}/{range}.pbf',sprite:`tripasset://assets/vector/sprites/${dark?'dark':'light'}`,sources,layers};
}
function providerStyle(p){if(p==='vector')return vectorStyle();const t=DATA.providers[p].tile_template;const style={version:8,sources:{base:{type:'raster',tiles:[t],tileSize:256,attribution:DATA.providers[p].attribution}},layers:[{id:'base',type:'raster',source:'base'}]};if(p==='satellite'){const labels=vectorStyle({labelsOnly:true});style.sources.basemap=labels.sources.basemap;style.glyphs=labels.glyphs;style.sprite=labels.sprite;style.layers.push(...labels.layers);}return style;}
function mapVisualSnapshot(map=photoMap){return {styleLoaded:!!map?.isStyleLoaded?.(),tilesLoaded:map?.areTilesLoaded?.()!==false,moving:!!map?.isMoving?.(),zooming:!!map?.isZooming?.(),localPending:state.localAssets.pending,resourceVersion:state.localAssets.completed+state.localAssets.failed,provider:state.provider,providerHealth:state.providerHealth.vector,localAssets:state.localAssets.status};}
function waitForMapVisualReady(map,timeout=30000){state.mapVisualReady=false;return new Promise((resolve,reject)=>{let stableFrames=0,lastVersion=-1,renderedVersion=-1,renderSeen=false,idleSeen=false,postIdleRenderSeen=false,finished=false,timer=0,raf=0;const cleanup=()=>{clearTimeout(timer);cancelAnimationFrame(raf);for(const event of ['idle','render','sourcedata','styledata'])map.off(event,trigger);};const finish=(error,value)=>{if(finished)return;finished=true;cleanup();if(error)reject(error);else resolve(value);};const check=()=>{if(finished)return;const snapshot=mapVisualSnapshot(map),ready=snapshot.styleLoaded&&snapshot.tilesLoaded&&!snapshot.moving&&!snapshot.zooming&&snapshot.localPending===0&&snapshot.provider==='vector'&&snapshot.providerHealth==='ready'&&snapshot.localAssets==='ready'&&renderSeen&&idleSeen&&postIdleRenderSeen&&renderedVersion===snapshot.resourceVersion;if(!ready){stableFrames=0;lastVersion=-1;return;}if(snapshot.resourceVersion===lastVersion)stableFrames++;else{lastVersion=snapshot.resourceVersion;stableFrames=1;}if(stableFrames>=3)finish(null,{...snapshot,stableFrames,renderSeen,idleSeen,postIdleRenderSeen});else raf=requestAnimationFrame(check);};function trigger(event){const snapshot=mapVisualSnapshot(map);if(event?.type==='sourcedata'||event?.type==='styledata'){idleSeen=false;postIdleRenderSeen=false;}if(event?.type==='idle'&&snapshot.localPending===0){idleSeen=true;postIdleRenderSeen=false;map.triggerRepaint?.();}if(event?.type==='render'&&snapshot.localPending===0){renderSeen=true;renderedVersion=snapshot.resourceVersion;if(idleSeen)postIdleRenderSeen=true;}stableFrames=0;lastVersion=-1;check();}for(const event of ['idle','render','sourcedata','styledata'])map.on(event,trigger);timer=setTimeout(()=>finish(new Error('Smart map visual readiness timed out'),null),timeout);check();});}
function probeImage(url,timeout=2600,tag='health'){return new Promise(resolve=>{const img=new Image();let done=false;const end=v=>{if(done)return;done=true;clearTimeout(timer);img.onload=img.onerror=null;resolve(v)};const timer=setTimeout(()=>end(false),timeout);img.onload=()=>end(img.naturalWidth>0);img.onerror=()=>end(false);img.referrerPolicy='no-referrer';img.src=url+(url.includes('?')?'&':'?')+tag+'='+(++state.runtime.probeSequence);});}
async function testProvider(p){if(p==='vector'){const ok=state.providerHealth.vector==='ready'&&state.localAssets.status==='ready';if(!ok)recordRuntimeEvent('health_failure','vector',{reason:'local_assets_not_ready'});return ok;}const cfg=DATA.providers[p];if(!cfg){state.providerHealth[p]='failed';return false;}if(cfg.requires_api_key){state.providerHealth[p]='failed';recordRuntimeEvent('health_failure',p,{reason:'api_key_required'});renderProviderState();return false;}state.providerHealth[p]='loading';state.providerStats[p].healthProbes++;recordRuntimeEvent('health_probe_started',p);renderProviderState();const ok=await probeImage(cfg.health_probe);state.providerHealth[p]=ok?'ready':'failed';recordRuntimeEvent(ok?'health_probe_passed':'health_probe_failed',p);renderProviderState();return ok;}
function tileUrlAt(p,lat,lon,z){const n=2**z,rad=lat*Math.PI/180,x=Math.floor((lon+180)/360*n),y=Math.floor((1-Math.log(Math.tan(rad)+1/Math.cos(rad))/Math.PI)/2*n);return DATA.providers[p].tile_template.replace('{z}',z).replace('{x}',x).replace('{y}',y);}
async function testViewportProvider(p){const first=DATA.markers.find(markerVisible),center=first||DATA.region_cfg[state.region].center,z=state.region==='overall'&&state.date==='all'?6:11;state.providerStats[p].viewportProbes++;recordRuntimeEvent('viewport_probe_started',p,{zoom:z});const ok=await probeImage(tileUrlAt(p,center.lat,center.lon,z),2800,'viewport');if(!ok){state.providerHealth[p]='failed';recordRuntimeEvent('viewport_probe_failed',p,{zoom:z});renderProviderState();}else recordRuntimeEvent('viewport_probe_passed',p,{zoom:z});return ok;}
function returnToSmart(provider,reason){state.providerStats[provider].fallbacks++;state.providerHealth[provider]='failed';if(state.provider===provider)state.provider='vector';recordRuntimeEvent('fallback_to_smart',provider,{reason,active:state.provider});document.getElementById('fallbackNote').textContent=u('providerFailure');renderControls();persistState();const smartAlreadyActive=state.provider==='vector'&&renderedProvider==='vector'&&renderedTheme===state.theme&&state.localAssets.status==='ready'&&state.mapVisualReady;return state.provider==='vector'?(smartAlreadyActive?Promise.resolve(true):drawMap(true)):Promise.resolve(false);}
async function chooseProvider(p){if(!['vector','satellite'].includes(p))return false;if(p==='vector'){state.provider='vector';document.getElementById('fallbackNote').textContent=u('providerReady');renderControls();persistState();return (await drawMap(true))!==false&&state.provider==='vector'&&state.localAssets.status==='ready';}const ok=await testProvider(p)&&await testViewportProvider(p);if(!ok){await returnToSmart(p,'probe_failure');return false;}state.provider=p;state.runtime.providerSwitches++;recordRuntimeEvent('provider_switch',p,{from:'vector'});document.getElementById('fallbackNote').textContent=`${u(p)} · ${u('liveReady')}`;renderControls();persistState();const rendered=await drawMap(true);if(rendered===false||state.provider!==p){if(state.provider===p)await returnToSmart(p,'render_failure');return false;}return true;}
function renderProviderState(){const el=document.getElementById('providerState'),health=state.providerHealth[state.provider]||'untested',failed=health==='failed';el.textContent=state.provider==='vector'&&health==='ready'?u('providerReady'):state.provider==='vector'?`${u('vector')} · ${failed?(state.lang==='ko'?'사용 불가':'Unavailable'):(state.lang==='ko'?'확인 중':'Checking')}`:`${u(state.provider)} · ${health==='ready'?(state.lang==='ko'?'준비 완료':'Ready'):failed?(state.lang==='ko'?'사용 불가':'Unavailable'):(state.lang==='ko'?'확인 중':'Checking')}`;el.className='provider-state '+(failed?'failed':health==='ready'?'ready':'');const feedback=document.getElementById('providerFeedback');if(feedback)feedback.textContent=failed?u('providerFailure'):state.provider==='vector'?u('providerReady'):`${u(state.provider)} · ${u('liveReady')}`;document.querySelectorAll('[data-provider]').forEach(b=>{const p=b.dataset.provider;b.dataset.health=state.providerHealth[p]||'untested';b.title=(DATA.providers[p]?.label||p)+' · '+(state.providerHealth[p]||'untested');b.setAttribute('aria-pressed',state.provider===p);});}
function baseTraces(){const c=DATA.region_cfg[state.region].center;return [{type:'scattermap',lat:[c.lat],lon:[c.lon],mode:'markers',marker:{size:1,opacity:0},hoverinfo:'skip',showlegend:false}];}
function visibleRouteFeatures(){const features=[];for(const l of DATA.legs){if(!legVisible(l))continue;const active=l.routes.filter(r=>state.routes.has(r)),geometry=GEOMETRY[l.leg_id],transfer=l.render_style==='transfer_dots',branch=l.branch_kind||'main',kind=transfer?'transfer':branch==='swap'?'option':['bonus','conditional','recovery','choice'].includes(branch)?branch:'local',coords=geometry?.coordinates||[[l.from_latlon[1],l.from_latlon[0]],[l.to_latlon[1],l.to_latlon[0]]];active.forEach((route,i)=>{const fromOcc=markerByKey[l.from]?.occurrences.find(o=>o.route===route&&o.date.startsWith(l.date));const toOcc=markerByKey[l.to]?.occurrences.find(o=>o.route===route&&o.date.startsWith(l.date));features.push({type:'Feature',geometry:{type:'LineString',coordinates:coords},properties:{leg_id:l.leg_id,label:l.label,mode:l.mode,note:l.note,date:l.date,route,color:routeMeta[route].color,offset:(i-(active.length-1)/2)*(transfer?3.2:3),kind,branch,status:geometry?.status||'conceptual_fallback',distance_km:geometry?.distance_km||0,time:[fromOcc?.time,toOcc?.time].filter(Boolean).map(tr).join(' → ')}})});}return features;}
function installRouteLayers(map){
  const add=()=>{
    if(map.getSource('trip-routes'))return;
    map.addSource('trip-routes',{type:'geojson',data:{type:'FeatureCollection',features:visibleRouteFeatures()}});
    const tip=document.getElementById('routeTip'),patterns={transfer:[3,2],conditional:[5,2],option:[4,2],bonus:[1,2.4],recovery:[8,3],choice:[2,2]},routePatterns={solid:null,dash:[5,2],dot:[1.2,2.2],dashdot:[5,1.4,1.2,1.4]};
    for(const kind of ['transfer','local','conditional','option','bonus','recovery','choice']){
      const kindFilter=['==',['get','kind'],kind],transfer=kind==='transfer',faint=kind==='bonus',colorWidth=transfer?4:kind==='local'?3.8:3.5,casingWidth=colorWidth+2;
      for(const route of ROUTES){
        const routeFilter=['all',kindFilter,['==',['get','route'],route]],routePattern=kind==='local'?(routePatterns[routeMeta[route].pattern]||null):patterns[kind],casingPaint={'line-color':state.theme==='dark'?'#101a25':'#fff','line-width':casingWidth,'line-opacity':faint?.78:.97,'line-offset':['get','offset']};
        if(routePattern)casingPaint['line-dasharray']=routePattern;
        map.addLayer({id:`trip-${kind}-${route}-casing`,type:'line',source:'trip-routes',filter:routeFilter,minzoom:0,maxzoom:24,layout:{'line-cap':'round','line-join':'round'},paint:casingPaint});
      }
      for(const route of ROUTES){
        const routeFilter=['all',kindFilter,['==',['get','route'],route]],routePattern=kind==='local'?(routePatterns[routeMeta[route].pattern]||null):patterns[kind],paint={'line-color':routeMeta[route].color,'line-width':colorWidth,'line-opacity':faint?.86:1,'line-offset':['get','offset']};
        if(routePattern)paint['line-dasharray']=routePattern;
        map.addLayer({id:`trip-${kind}-${route}`,type:'line',source:'trip-routes',filter:routeFilter,minzoom:0,maxzoom:24,layout:{'line-cap':'round','line-join':'round'},paint});
      }
      map.addLayer({id:`trip-${kind}-hit`,type:'line',source:'trip-routes',filter:kindFilter,minzoom:0,maxzoom:24,paint:{'line-color':'#fff','line-width':22,'line-opacity':.001}});
      const id=`trip-${kind}-hit`;
      map.on('mousemove',id,e=>{
        const p=e.features?.[0]?.properties;if(!p||e.originalEvent?.target?.closest?.('.photo-cluster,.photo-marker')||document.getElementById('previewCard').classList.contains('show'))return;
        map.getCanvas().style.cursor='pointer';
        const branch=['swap','bonus','conditional','recovery','choice'].includes(p.branch)?tierLabel(p.branch):u('shared');
        tip.innerHTML=`<b style="color:${p.color}">${esc(p.route)} · ${esc(dateLabel(p.date))} · ${esc(tr(p.label))}</b><span>${esc(branch)} · ${esc(p.time||'')} · ${esc(modeLabel(p.mode))}${p.distance_km?` · ${Number(p.distance_km).toFixed(1)} km`:''}</span><span>${esc(tr(p.note||''))}</span><small>${p.status==='routed_osm'?(state.lang==='ko'?'로컬 캐시 OSM 참조 경로 · 도로 폐쇄 별도 확인':'Locally cached OSM reference · verify closures'):u('conceptual')}</small>`;
        tip.classList.add('show');tip.style.left=Math.min(e.point.x+14,map.getCanvas().clientWidth-275)+'px';
        const schedule=document.getElementById('mapSchedule'),maxTop=schedule.offsetTop-tip.offsetHeight-8;tip.style.top=Math.max(54,Math.min(e.point.y+14,maxTop))+'px';
      });
      map.on('mouseleave',id,()=>{map.getCanvas().style.cursor='';tip.classList.remove('show')});
      map.on('click',id,e=>{e.originalEvent.stopPropagation();setTimeout(()=>tip.classList.remove('show'),4500)});
    }
  };
  if(map.isStyleLoaded())add();else map.once('load',add);
}
function fitVisibleMap(map){const visible=DATA.markers.filter(markerVisible);if(!visible.length)return;const routePoints=visibleRouteFeatures().filter(f=>f.properties.kind!=='transfer').flatMap(f=>f.geometry.coordinates),points=[...visible.map(m=>[m.lon,m.lat]),...routePoints];if(points.length===1){map.jumpTo({center:points[0],zoom:13.1});return;}const pad=map.getCanvas().clientWidth<=800?{top:105,right:34,bottom:112,left:34}:{top:185,right:78,bottom:124,left:78},focused=state.date!=='all'||state.region!=='overall';map.fitBounds([[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1]))],[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))]],{padding:pad,maxZoom:focused?12.8:7.8,duration:0});}
function watchLiveTiles(map,provider){
  if(provider==='vector')return;
  let failures=0,timer=null,lastTile='',finished=false;
  const fallback=reason=>{if(finished||state.provider!==provider)return;finished=true;clearTimeout(timer);returnToSmart(provider,reason);};
  const checkViewport=async()=>{
    if(state.provider!==provider)return;
    const center=map.getCenter(),z=Math.max(0,Math.min(18,Math.floor(map.getZoom())));
    const url=tileUrlAt(provider,center.lat,center.lng,z);if(url===lastTile)return;lastTile=url;
    if(!await probeImage(url,2800,'viewport')){state.providerStats[provider].tileErrors++;recordRuntimeEvent('viewport_tile_failed',provider,{zoom:z});fallback('viewport_tile_failure');}
  };
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(checkViewport,350)};
  map.on('moveend',schedule);schedule();
  const onError=event=>{if(state.provider!==provider)return;const message=String(event.error?.message||event.message||'');if(event.sourceId!=='base'&&!/tile|fetch|image|network/i.test(message))return;state.providerStats[provider].tileErrors++;recordRuntimeEvent('provider_tile_error',provider,{source:event.sourceId||null,message:message.slice(0,180)});if(++failures>=2)fallback('map_tile_errors');};
  map.on('error',onError);
  map.__tripCleanup=()=>{finished=true;clearTimeout(timer);map.off('moveend',schedule);map.off('error',onError);};
}
function visibleMarkerBounds(){const m=DATA.markers.filter(markerVisible);if(!m.length)return null;return {lat:[Math.min(...m.map(x=>x.lat)),Math.max(...m.map(x=>x.lat))],lon:[Math.min(...m.map(x=>x.lon)),Math.max(...m.map(x=>x.lon))]};}
function ringFor(m){const active=m.routes.filter(r=>state.routes.has(r));const colors=active.map(r=>routeMeta[r].color);if(colors.length===1)return colors[0];return `conic-gradient(${colors.map((c,i)=>`${c} ${i/colors.length*100}% ${(i+1)/colors.length*100}%`).join(',')})`;}
function updateMarkerLabels(map=photoMap){if(!map||map!==photoMap)return;const zoom=map.getZoom(),placed=[];photoMarkers.forEach((marker,placeKey)=>{const el=marker.getElement(),label=el.querySelector('.marker-callout'),m=markerByKey[placeKey];if(!label)return;label.style.display='none';if(!m||!markerVisible(m)||zoom<9.3||el.style.display==='none')return;const p=map.project([m.lon,m.lat]),w=Math.min(175,Math.max(105,placeName(placeKey).length*6.2)),box={left:p.x-w/2,top:p.y+18,right:p.x+w/2,bottom:p.y+100};if(box.left<8||box.right>map.getCanvas().clientWidth-8||box.bottom>map.getCanvas().clientHeight-12)return;if(placed.some(b=>box.left<b.right+8&&box.right>b.left-8&&box.top<b.bottom+5&&box.bottom>b.top-5))return;placed.push(box);label.style.display='block';});}
function showClusterPreview(members,event,center,anchor=null){const hero=members[0],regions=[...new Set(members.map(m=>DATA.place_region[m.place_key]))],region=regions.length===1?u(regions[0]):u('overall'),card=document.getElementById('previewCard'),active=[...new Set(members.flatMap(m=>m.routes.filter(r=>state.routes.has(r))))];previewReturnTarget=anchor||document.activeElement;document.getElementById('routeTip').classList.remove('show');card.innerHTML=`<img class="preview-media" src="${photoSrc(photoPath(hero.place_key,'hero','medium'))}" alt=""><div class="preview-body"><div id="previewTitle" class="preview-title">${esc(region)} · ${members.length} ${u('stops')}</div><div id="previewDescription" class="preview-meta">${esc(active.join(' / '))} · ${state.date==='all'?u('allDates'):esc(dateLabel(state.date))}</div><div class="preview-why">${esc(members.slice(0,3).map(m=>placeName(m.place_key)).join(' · '))}${members.length>3?' …':''}</div><button type="button" class="preview-action">${u('explore')} ↗</button></div>`;card.querySelector('.preview-action').onclick=e=>{e.stopPropagation();photoMap.easeTo({center,zoom:Math.max(photoMap.getZoom()+2.2,11),duration:400});hidePreview()};card.classList.add('show');card.setAttribute('aria-hidden','false');positionPreview(event,card);if(event?.detail===0)card.querySelector('.preview-action').focus({preventScroll:true});}
function updatePhotoClusters(map=photoMap){if(!map||map!==photoMap)return;clusterMarkers.forEach(x=>x.remove());clusterMarkers=[];const entries=DATA.markers.filter(markerVisible).map(place=>({place,marker:photoMarkers.get(place.place_key)})).filter(entry=>entry.marker),n=entries.length,parent=Array.from({length:n},(_,i)=>i);const root=i=>{while(parent[i]!==i)i=parent[i];return i};const pts=entries.map(entry=>map.project([entry.place.lon,entry.place.lat]));const threshold=map.getZoom()<7?52:36;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(entries[i].place.place_key!==state.selected&&entries[j].place.place_key!==state.selected&&Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y)<threshold)parent[root(j)]=root(i);const groups={};for(let i=0;i<n;i++)(groups[root(i)]??=[]).push(i);photoMarkers.forEach(marker=>marker.getElement().style.display='');for(const indexes of Object.values(groups)){if(indexes.length<2)continue;indexes.forEach(i=>entries[i].marker.getElement().style.display='none');const members=indexes.map(i=>entries[i].place),lat=members.reduce((s,m)=>s+m.lat,0)/members.length,lon=members.reduce((s,m)=>s+m.lon,0)/members.length,hero=members[0],center=[lon,lat];const el=document.createElement('button');el.type='button';el.className='photo-cluster';el.title=`${members.length} ${u('stops')} · ${u('explore')}`;el.setAttribute('aria-label',el.title);const regions=[...new Set(members.map(m=>DATA.place_region[m.place_key]))];if(map.getZoom()<7&&regions.length===1)el.dataset.label=u(regions[0]);el.innerHTML=`<img src="${photoSrc(photoPath(hero.place_key,'hero','thumb'))}" alt="" draggable="false"><span class="cluster-count">${members.length}</span>`;el.addEventListener('mouseenter',e=>{if(!state.touch)showClusterPreview(members,e,center,el)});el.addEventListener('mouseleave',()=>{if(!state.touch)hidePreview()});el.addEventListener('focus',e=>showClusterPreview(members,e,center,el));el.addEventListener('click',e=>{e.stopPropagation();showClusterPreview(members,e,center,el);map.easeTo({center,zoom:Math.max(map.getZoom()+2.2,11),duration:400});});clusterMarkers.push(new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(center).addTo(map));}updateMarkerLabels(map);}
function installPhotoMarkers(map){photoMap=map;photoMarkers=new Map();const update=()=>updatePhotoClusters(map);map.__tripPhotoCleanup=()=>{map.off('zoomend',update);map.off('moveend',update);map.__tripPhotoCleanup=null;};DATA.markers.filter(markerVisible).forEach(m=>{const el=document.createElement('button');el.type='button';el.className='photo-marker'+(state.selected===m.place_key?' selected':'')+(m.source_class==='official_gap_audit'?' audited':'');el.dataset.placeKey=m.place_key;el.setAttribute('aria-label',`${u('selectStop')}: ${placeName(m.place_key)}`);el.title=placeName(m.place_key);el.style.background=ringFor(m);const occ=preferredOccurrence(m),seq=state.date==='all'&&state.routes.size>1?DATA.markers.indexOf(m)+1:occ?.seq||DATA.markers.indexOf(m)+1,tier=tierFor(m);el.innerHTML=`<img src="${photoSrc(photoPath(m.place_key,'hero','thumb'))}" alt="" draggable="false"><span class="photo-seq">${seq}</span>${m.source_class==='official_gap_audit'?'<span class="audit-star" aria-hidden="true">★</span>':''}<span class="marker-callout"><b>${esc(placeName(m.place_key))}</b>${state.lang==='ko'?`<em>${esc(placeKo(m.place_key))}</em>`:''}<small>${esc(tierLabel(tier))}${state.date!=='all'&&occ?.time?` · ${esc(tr(occ.time))}`:''}</small></span>`;bindLocalImageFailures(el);el.addEventListener('mouseenter',e=>{if(!state.touch)showPreview(m.place_key,{event:e,anchor:el})});el.addEventListener('mouseleave',()=>{if(!state.touch){clearTimeout(window.__previewTimer);window.__previewTimer=setTimeout(()=>hidePreview(),220)}});el.addEventListener('focus',()=>{if(suppressMarkerPreviewFocus){suppressMarkerPreviewFocus=false;return}showPreview(m.place_key,{anchor:el})});el.addEventListener('click',e=>{e.stopPropagation();showPreview(m.place_key,{event:e,anchor:el,keyboard:e.detail===0})});photoMarkers.set(m.place_key,new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([m.lon,m.lat]).addTo(map));});map.on('zoomend',update);map.on('moveend',update);update();}
function installLegLabels(map){legMarkers.forEach(m=>m.remove());legMarkers=[];for(const leg of DATA.legs.filter(l=>l.render_style==='transfer_dots'&&legVisible(l))){const points=GEOMETRY[leg.leg_id]?.coordinates;if(!points?.length)continue;const midpoint=points[Math.floor(points.length/2)],routes=leg.routes.filter(r=>state.routes.has(r)),el=document.createElement('button');el.type='button';el.className='route-leg-label';el.innerHTML=`<b>${esc(dateLabel(leg.date))} · ${esc(tr(leg.label))}</b><span>${routes.map(r=>`<i style="background:${routeMeta[r].color}">${r}</i>`).join('')}</span>`;el.title=`${dateLabel(leg.date)} · ${tr(leg.label)}`;el.onclick=async e=>{e.stopPropagation();state.date=leg.date;await filtersChanged()};const offset=leg.date==='10/9'?[0,-22]:leg.date==='10/10'?[0,22]:[0,0];legMarkers.push(new maplibregl.Marker({element:el,anchor:'center',offset}).setLngLat(midpoint).addTo(map));}if(map._tripLegUpdate)map.off('zoomend',map._tripLegUpdate);const update=()=>legMarkers.forEach(m=>m.getElement().style.display=map.getZoom()<9.3?'block':'none');map._tripLegUpdate=update;map.on('zoomend',update);update();}
function drawMap(preserve=true,options={}){state.runtime.drawRequests++;state.mapVisualReady=false;const waitForVisual=options.waitForVisual!==false;const perform=async()=>{
  const previous=photoMap,activeProvider=state.provider,same=previous&&renderedProvider===activeProvider&&renderedTheme===state.theme;
  previous?.__tripPhotoCleanup?.();
  clusterMarkers.forEach(m=>m.remove());clusterMarkers=[];photoMarkers.forEach(m=>m.remove());photoMarkers=new Map();legMarkers.forEach(m=>m.remove());legMarkers=[];
  if(same&&state.localAssets.status==='ready'){previous.getSource('trip-routes')?.setData({type:'FeatureCollection',features:visibleRouteFeatures()});if(!preserve)fitVisibleMap(previous);installPhotoMarkers(previous);installLegLabels(previous);renderControls();if(!waitForVisual)return true;const ready=await waitForMapVisualReady(previous);state.mapVisualReady=true;return !!ready;}
  const view=preserve&&previous?{center:previous.getCenter(),zoom:previous.getZoom()}:null;if(previous){previous.__tripCleanup?.();previous.remove();state.runtime.mapRemovals++;}photoMap=null;
  let map;
  try{
    const r=DATA.region_cfg[state.region];map=new maplibregl.Map({container:'map',style:providerStyle(activeProvider),center:[r.center.lon,r.center.lat],zoom:r.zoom,attributionControl:false,dragRotate:false,pitchWithRotate:false,maxZoom:18});photoMap=map;renderedProvider=activeProvider;renderedTheme=state.theme;state.runtime.mapCreations++;
    map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');
    map.on('error',event=>{console.error('Map layer error:',event.error);recordRuntimeEvent('map_error',activeProvider,{source:event.sourceId||null,message:String(event.error?.message||event.message||event.error||'').slice(0,180)});if(activeProvider==='vector'&&localMapError(event))showMapFailure(event.error||event,'local_map_asset');});
    const loaded=await Promise.race([new Promise(resolve=>map.once('load',()=>resolve(true))),new Promise(resolve=>setTimeout(()=>resolve(false),7000))]);if(photoMap!==map)return false;
    if(!loaded){if(activeProvider==='vector')showMapFailure(new Error('Smart map style did not load'),'style_timeout');else returnToSmart(activeProvider,'style_timeout');map.__tripCleanup?.();map.remove();photoMap=null;state.runtime.mapRemovals++;return false;}
    if(activeProvider==='vector'&&state.localAssets.status!=='ready'){map.__tripCleanup?.();map.remove();photoMap=null;state.runtime.mapRemovals++;return false;}
    if(view)map.jumpTo(view);else fitVisibleMap(map);watchLiveTiles(map,activeProvider);installRouteLayers(map);installPhotoMarkers(map);installLegLabels(map);renderControls();if(!waitForVisual)return true;const ready=await waitForMapVisualReady(map);state.mapVisualReady=true;return !!ready;
  }catch(error){if(activeProvider==='vector')showMapFailure(error,'map_render');else returnToSmart(activeProvider,'map_render');if(map){map.__tripCleanup?.();map.remove();state.runtime.mapRemovals++;}photoMap=null;return false;}
};drawQueue=drawQueue.catch(()=>false).then(perform);return drawQueue;}
function preferredOccurrence(x){const occ=x.occurrences.filter(o=>state.routes.has(o.route)&&(state.date==='all'||dateMatchesOccurrence(o)));return occ[0]||x.occurrences.find(o=>state.routes.has(o.route))||x.occurrences[0];}
function positionPreview(event,card){clearTimeout(window.__previewTimer);const wrap=document.querySelector('.mapwrap').getBoundingClientRect();let left=(event?.clientX||wrap.left+wrap.width*.52)-wrap.left+14,top=(event?.clientY||wrap.top+wrap.height*.46)-wrap.top+14;const w=Math.min(320,wrap.width-16),h=Math.min(310,wrap.height-16);if(left+w>wrap.width)left=Math.max(8,left-w-28);if(top+h>wrap.height)top=Math.max(8,top-h-28);card.style.left=left+'px';card.style.top=top+'px';}
function showPreview(k,p){const x=markerByKey[k];if(!x)return;const card=document.getElementById('previewCard'),signature=[k,state.lang,state.date,[...state.routes].sort().join(',')].join('|');previewReturnTarget=p?.anchor||document.activeElement;document.getElementById('routeTip').classList.remove('show');if(card.dataset.previewSignature!==signature){const o=preferredOccurrence(x),groups=groupOccurrences(x).slice(0,3),tier=tierFor(x);card.innerHTML=`<img class="preview-media" src="${photoSrc(photoPath(k,'hero','medium'))}" alt="${esc(placeName(k))}"><div class="preview-body"><div id="previewTitle" class="preview-title">${esc(placeName(k))}</div>${state.lang==='ko'?`<div class="preview-sub">${esc(placeKo(k))}</div>`:''}<div class="preview-tier ${esc(tier)}">${esc(tierLabel(tier))}${x.source_class==='official_gap_audit'?` · ${u('auditAdded')}`:''}</div><div id="previewDescription" class="preview-meta">${groups.map(g=>`<span>${esc(g.routes.join('/'))} · ${esc(dateLabel(g.date))} · ${esc(tr(g.time||'—'))} · ${esc(tr(g.status||''))}</span>`).join('')}</div><div class="preview-why"><b>${u('whyNow')}</b> ${esc(tr(o?.reason||x.why))}</div>${o?.advantage?`<div class="preview-adv">${u('advantage')}: ${esc(tr(o.advantage))}</div>`:''}<button type="button" class="preview-action">${u('details')} ↗</button></div>`;card.querySelector('.preview-action').onclick=e=>{e.stopPropagation();selectPlace(k,{focus:false,openDetails:true});hidePreview()};card.dataset.previewSignature=signature;}card.classList.add('show');card.setAttribute('aria-hidden','false');positionPreview(p?.event,card);if(p?.keyboard)card.querySelector('.preview-action').focus({preventScroll:true});}
function hidePreview({returnFocus=false}={}){clearTimeout(window.__previewTimer);const card=document.getElementById('previewCard');card.classList.remove('show');card.setAttribute('aria-hidden','true');if(returnFocus&&previewReturnTarget?.isConnected){suppressMarkerPreviewFocus=true;previewReturnTarget.focus({preventScroll:true});setTimeout(()=>{suppressMarkerPreviewFocus=false},0)}previewReturnTarget=null;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function groupOccurrences(x){const groups={};for(const o of x.occurrences.filter(o=>state.routes.has(o.route)&&(state.date==='all'||dateMatchesOccurrence(o)))){const sig=[o.date,o.time,o.title,o.reason,o.advantage,o.status].join('|');if(!groups[sig])groups[sig]={...o,routes:[]};groups[sig].routes.push(o.route);}return Object.values(groups);}
function renderDetail(k){
  const x=markerByKey[k],panel=document.getElementById('detailsPane');
  if(!x){const visible=DATA.markers.filter(markerVisible);panel.innerHTML=`<div class="stop-browser"><h2>${u('selectStop')}</h2><p>${u('browseHint')}</p>${visible.length?visible.map(m=>{const o=preferredOccurrence(m);return `<button type="button" class="stop-browser-card" data-browse-place="${esc(m.place_key)}"><img src="${photoSrc(photoPath(m.place_key,'hero','thumb'))}" alt=""><span><b>${esc(placeName(m.place_key))}</b>${state.lang==='ko'?`<small>${esc(placeKo(m.place_key))}</small>`:''}<small>${esc(dateLabel(o?.date||''))} · ${esc(tr(o?.time||'—'))} · ${esc(m.routes.filter(r=>state.routes.has(r)).join('/'))}</small><em>${esc(tr(o?.reason||m.why))}</em></span></button>`}).join(''):`<div class="empty">${u('noSlots')}</div>`}</div>`;panel.querySelectorAll('[data-browse-place]').forEach(b=>b.onclick=()=>selectPlace(b.dataset.browsePlace,{focus:true,openDetails:true}));renderMapFocus(null);return;}
  const chips=x.routes.filter(r=>state.routes.has(r)).map(r=>`<span class="chip" style="background:${routeMeta[r].color}">${r}</span>`).join('');
  const occ=groupOccurrences(x),now=preferredOccurrence(x);
  const photoRoles=state.lang==='ko'?[['대표 장면','hero'],['현장 경험','experience'],['규모·맥락','scale_context']]:[['HERO','hero'],['EXPERIENCE','experience'],['SCALE / CONTEXT','scale_context']];
  const tier=tierFor(x);
  panel.innerHTML=`<h2>${esc(placeName(k))}</h2>${state.lang==='ko'?`<div class="place-korean">${esc(placeKo(k))}</div>`:''}<div class="detail-sub"><span>${esc(tr(x.cluster))}</span><span>${esc(tr(x.role))}</span><span>${esc(x.score)}/100</span><span class="tier-chip ${esc(tier)}">${esc(tierLabel(tier))}</span></div><div class="routechips">${chips}</div>
  <div class="detail-glance"><div class="glance-label">${esc(tr(now?.status||''))} · ${esc(dateLabel(now?.date||''))} · ${esc(tr(now?.time||'—'))}</div><div class="glance-title">${u('whyNow')}</div><div>${esc(tr(now?.reason||x.why))}</div>${now?.advantage?`<div class="glance-adv">${u('advantage')}: ${esc(tr(now.advantage))}</div>`:''}</div>
  <div class="photo-grid">${photoRoles.map(([label,role])=>`<figure class="photo-slot" data-photo-role="${role.toUpperCase()}" data-photo-path="${photoPath(k,role,'medium')}"><img src="${photoSrc(photoPath(k,role,'medium'))}" alt="${esc(placeName(k))} — ${label}" loading="eager"><figcaption>${label}</figcaption></figure>`).join('')}</div>
  <div class="fact"><b>${u('whyPlace')}</b>${esc(tr(x.why))}</div><div class="fact"><b>${u('experience')}</b>${esc(tr(x.summary))}</div>
  <div class="fact"><b>${u('exactTiming')} · ${u('shared')}</b>${occ.length?occ.map(o=>`<div class="timeline-card no-map"><div class="tl-top"><div><div class="tl-title">${esc(tr(o.title))}</div><div class="tl-time">${esc(dateLabel(o.date))} · ${esc(tr(o.time||'—'))}</div></div><span class="status-chip">${esc(tr(o.status||''))}</span></div><div class="mini-routes">${o.routes.map(r=>`<span class="mini-route" style="background:${routeMeta[r].color}">${r}</span>`).join('')}</div><div class="tl-reason"><b>${u('whyNow')}:</b> ${esc(tr(o.reason))}</div><div class="adv">${u('advantage')}: ${esc(tr(o.advantage||'—'))}</div></div>`).join(''):`<div class="muted">${u('noSlots')}</div>`}</div>
  ${x.decision_rules?.length?`<div class="fact"><b>${u('decision')}</b>${x.decision_rules.map(d=>`<div class="decision"><b>${esc(decisionLabel(d.key))}</b><br>${esc(tr(d.text))}</div>`).join('')}</div>`:''}
  ${x.source_class==='official_gap_audit'?`<div class="fact audit-note"><b>★ ${u('auditAdded')}</b>${esc(tr(x.workbook_status||''))}</div>`:''}<div class="fact"><b>${u('directions')}</b><div class="muted">${x.lat.toFixed(5)}, ${x.lon.toFixed(5)}</div><a class="maps-link" href="${x.maps_url}" target="_blank" rel="noopener">${u('directions')} ↗</a></div>`;
  bindLocalImageFailures(panel);renderMapFocus(k);
}
function focusPlace(k){const x=markerByKey[k];if(!x||!photoMap)return;photoMap.easeTo({center:[x.lon,x.lat],zoom:13.3,duration:380});}
function selectPlace(k,{focus=true,openDetails=true}={}){state.selected=k;hidePreview();renderDetail(k);renderTimeline();updateMarkerEmphasis();if(focus)focusPlace(k);if(openDetails){document.querySelector('.route-guide')?.removeAttribute('open');const app=document.getElementById('app');if(app.classList.contains('panel-hidden'))setPanelHidden(false);setTab('details');document.getElementById('detailsPane')?.focus({preventScroll:true});}persistState();}
function updateMarkerEmphasis(){document.querySelectorAll('.photo-marker').forEach(el=>el.classList.toggle('selected',el.dataset.placeKey===state.selected));updatePhotoClusters();}
function routeMini(routes){return routes.filter(r=>state.routes.has(r)).map(r=>`<span class="mini-route" style="background:${routeMeta[r].color}">${r}</span>`).join('');}
function renderTimeline(){
  const pane=document.getElementById('timelinePane'),list=DATA.timeline.filter(timelineVisible),grouped={};
  for(const t of list)(grouped[t.date]??=[]).push(t);
  let html=`<div class="timeline-tools"><div><b>${u('timeline')}</b><div class="timeline-count">${list.length} ${u('stops')} · ${state.routes.size} ${u('routes').toLowerCase()}</div></div></div>`;
  for(const [date,arr] of Object.entries(grouped)){
    html+=`<section class="day"><div class="day-title">${esc(dateLabel(date))}</div>${arr.map(t=>{
      const mapped=t.spatial_keys.length>0,selected=state.selected&&t.spatial_keys.includes(state.selected),placeNames=t.spatial_keys.map(placeName).filter(Boolean);
      return `<button class="timeline-card ${selected?'selected':''} ${mapped?'':'no-map'} tier-${esc(t.schedule_tier||'main')}" data-timeline="${t.id}"><div class="tl-top"><div class="tl-title">${esc(timelineTitle(t))}</div><div class="tl-time">${esc(tr(t.time||'—'))}</div></div>${state.lang==='ko'&&t.spatial_keys.length===1?`<div class="place-korean">${esc(placeKo(t.spatial_keys[0]))}</div>`:''}<div class="tl-flags"><span>${t.route_specific?u('specific'):u('shared')}</span><span>${mapped?u('photoStop'):u('plan')}</span>${t.schedule_tier?`<span class="tier-chip ${esc(t.schedule_tier)}">${esc(tierLabel(t.schedule_tier))}</span>`:''}</div><div class="mini-routes">${routeMini(t.routes)}</div>${placeNames.length>1?`<div class="tl-place">${esc(placeNames.join(' · '))}</div>`:''}${t.mutually_exclusive_group?`<div class="choice-warning">↔ ${u('choiceWarning')}</div>`:''}<div class="tl-reason"><b>${u('whyNow')}:</b> ${esc(tr(t.reason))}</div><div class="adv"><b>${u('advantage')}:</b> ${esc(tr(t.advantage||'—'))}</div></button>`
    }).join('')}</section>`;
  }
  if(!list.length)html+=`<div class="empty">${u('noSlots')}</div>`;
  pane.innerHTML=html;
  pane.querySelectorAll('[data-timeline]').forEach(b=>b.onclick=()=>{const t=DATA.timeline.find(x=>x.id===b.dataset.timeline);if(t?.spatial_keys?.length)selectPlace(t.spatial_keys[0],{focus:true,openDetails:false});else renderPlanFocus(t);});
  renderMapSchedule();
}
function renderPlanFocus(t){const card=document.getElementById('mapFocus');if(!t)return;mapFocusReturnTarget=document.activeElement;card.innerHTML=`<div class="map-focus-head"><b id="mapFocusTitle">${esc(tr(t.title))}</b><button type="button" aria-label="${u('close')}">×</button></div><div class="map-focus-meta">${esc(dateLabel(t.date))} · ${esc(tr(t.time||'—'))} · ${esc(t.routes.filter(r=>state.routes.has(r)).join('/'))}</div><p>${esc(tr(t.reason))}</p><strong>${u('advantage')}: ${esc(tr(t.advantage||'—'))}</strong><small>${u('noMapped')}</small>`;card.setAttribute('role','dialog');card.setAttribute('aria-modal','false');card.setAttribute('aria-labelledby','mapFocusTitle');card.classList.add('show');card.setAttribute('aria-hidden','false');card.querySelector('button').onclick=()=>{card.classList.remove('show');card.setAttribute('aria-hidden','true');mapFocusReturnTarget?.focus?.({preventScroll:true});};}
function renderMapFocus(k){const card=document.getElementById('mapFocus');if(!card)return;const x=markerByKey[k];if(!x||(isMobile()&&state.tab==='details'&&!document.getElementById('app').classList.contains('panel-hidden'))){card.classList.remove('show');card.setAttribute('aria-hidden','true');card.innerHTML='';return;}mapFocusReturnTarget=document.activeElement;const occ=groupOccurrences(x),now=preferredOccurrence(x),tier=tierFor(x);card.innerHTML=`<div class="map-focus-head"><b id="mapFocusTitle">${esc(placeName(k))}</b><button type="button" aria-label="${u('close')}">×</button></div>${state.lang==='ko'?`<div class="place-korean">${esc(placeKo(k))}</div>`:''}<div class="preview-tier ${esc(tier)}">${esc(tierLabel(tier))}${x.source_class==='official_gap_audit'?` · ${u('auditAdded')}`:''}</div><div class="map-focus-meta">${occ.map(o=>`${esc(o.routes.join('/'))} · ${esc(dateLabel(o.date))} · ${esc(tr(o.time||'—'))} · ${esc(tr(o.status||''))}`).join('<br>')}</div><div class="map-focus-photo"><img src="${photoSrc(photoPath(k,'hero','medium'))}" alt="${esc(placeName(k))}"></div><p><b>${u('whyNow')}</b> ${esc(tr(now?.reason||x.why))}</p><strong>${u('advantage')}: ${esc(tr(now?.advantage||'—'))}</strong><button type="button" class="map-focus-details">${u('details')} ↗</button>`;bindLocalImageFailures(card);card.setAttribute('role','dialog');card.setAttribute('aria-modal','false');card.setAttribute('aria-labelledby','mapFocusTitle');card.classList.add('show');card.setAttribute('aria-hidden','false');card.querySelector('.map-focus-head button').onclick=()=>{card.classList.remove('show');card.setAttribute('aria-hidden','true');mapFocusReturnTarget?.focus?.({preventScroll:true});};card.querySelector('.map-focus-details').onclick=()=>selectPlace(k,{focus:false,openDetails:true});}
function renderMapSchedule(){
  const ribbon=document.getElementById('dateRibbon'),strip=document.getElementById('mapSchedule');if(!ribbon||!strip)return;
  ribbon.innerHTML=`<button type="button" class="day-chip ${state.date==='all'?'active':''}" data-day="all">${u('allDates')}</button>`+DATA.dates.map(d=>`<button type="button" class="day-chip ${state.date===d.key?'active':''}" data-day="${d.key}">${esc(dateLabel(d.key))}</button>`).join('');
  ribbon.querySelectorAll('[data-day]').forEach(b=>b.onclick=async()=>{state.date=b.dataset.day;await filtersChanged()});
  if(state.date==='all'){
    strip.innerHTML=DATA.dates.map(d=>{const rows=DATA.timeline.filter(t=>t.date_key===d.key&&routeIntersects(t.routes)&&(state.region==='overall'||t.regions.includes(state.region))),mapped=rows.find(t=>t.spatial_keys.length),title=mapped?placeName(mapped.spatial_keys[0]):tr(rows[0]?.title||'—');return `<button class="map-slot day-overview" data-day="${d.key}"><b>${esc(dateLabel(d.key))}</b><span>${esc(title)}</span><small>${rows.length} ${u('stops')} · ${esc([...new Set(rows.flatMap(x=>x.routes))].filter(r=>state.routes.has(r)).join('/'))}</small></button>`}).join('');
    strip.querySelectorAll('[data-day]').forEach(b=>b.onclick=async()=>{state.date=b.dataset.day;await filtersChanged()});return;
  }
  const rows=DATA.timeline.filter(timelineVisible),groups=new Map();
  for(const t of rows){const sig=[t.time,t.title,t.reason,t.advantage,t.spatial_keys.join(',')].join('|');if(!groups.has(sig))groups.set(sig,{...t,routes:[]});groups.get(sig).routes.push(...t.routes.filter(r=>state.routes.has(r)));}
  strip.innerHTML=[...groups.values()].map(t=>`<button class="map-slot ${t.spatial_keys.length?'mapped':'plan-slot'} tier-${esc(t.schedule_tier||'main')} ${state.selected&&t.spatial_keys.includes(state.selected)?'selected':''}" data-slot="${t.id}" style="border-left-color:${t.route_specific?routeMeta[t.routes[0]].color:''}"><b>${esc(tr(t.time||'—'))}</b><span>${esc(timelineTitle(t))}</span><small>${state.lang==='ko'&&t.spatial_keys.length===1?esc(placeKo(t.spatial_keys[0]))+' · ':''}${esc([...new Set(t.routes)].join('/'))} · ${t.schedule_tier?esc(tierLabel(t.schedule_tier)):t.spatial_keys.length?u('photoStop'):u('plan')}</small></button>`).join('')||`<div class="map-slot">${u('noSlots')}</div>`;
  strip.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const t=rows.find(x=>x.id===b.dataset.slot);if(t?.spatial_keys.length)selectPlace(t.spatial_keys[0],{focus:true,openDetails:false});else renderPlanFocus(t)});
}
function routeExplanationHTML(r,{compact=false}={}){const x=routeMeta[r],n=routeNarrative(r),scores=Object.entries(x.score||{});return `<div class="route-explain-head"><div><b style="color:${x.color}">${esc(r)} · ${esc(tr(x.title))}</b><small>${esc(tr(x.subtitle||''))}</small></div>${compact?'':`<button type="button" class="route-explain-close" aria-label="${u('close')}">×</button>`}</div><div class="route-explain-grid"><div class="route-explain-item"><b>${u('bestFor')}</b>${esc(n.best_for)}</div><div class="route-explain-item"><b>${u('tradeoff')}</b>${esc(n.tradeoff)}</div><div class="route-explain-item"><b>${u('routeRule')}</b>${esc(n.decision_rule)}</div><div class="route-explain-item"><b>${u('regretGuard')}</b>${esc(n.regret_guard)}</div></div>${scores.length?`<div class="route-explain-score" aria-label="${u('routeScore')}">${scores.map(([k,v])=>`<span>${esc(scoreLabel(k))} ${esc(v)}/10</span>`).join('')}</div>`:''}`;}
let routeExplainPinned=null,routeExplainTimer=0;
function hideRouteExplanation(force=false){if(routeExplainPinned&&!force)return;clearTimeout(routeExplainTimer);routeExplainPinned=null;const tip=document.getElementById('routeExplain');tip?.classList.remove('show');tip?.setAttribute('aria-hidden','true');document.querySelectorAll('[data-route-info]').forEach(b=>b.setAttribute('aria-expanded','false'));if(force&&routeExplainReturnTarget?.isConnected){suppressRouteInfoFocus=true;routeExplainReturnTarget.focus({preventScroll:true});setTimeout(()=>{suppressRouteInfoFocus=false},0)}routeExplainReturnTarget=null;}
function showRouteExplanation(r,anchor,{pinned=false}={}){const tip=document.getElementById('routeExplain'),x=routeMeta[r];if(!tip||!anchor||!x)return;clearTimeout(routeExplainTimer);routeExplainPinned=pinned?r:null;routeExplainReturnTarget=anchor;tip.style.setProperty('--route-color',x.color);tip.innerHTML=routeExplanationHTML(r);tip.querySelector('.route-explain-head b')?.setAttribute('id','routeExplainTitle');tip.classList.add('show');tip.setAttribute('aria-hidden','false');document.querySelectorAll('[data-route-info]').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.routeInfo===r&&pinned)));const rect=anchor.getBoundingClientRect(),width=tip.offsetWidth,height=tip.offsetHeight,left=Math.max(10,Math.min(rect.left,window.innerWidth-width-10));let top=rect.bottom+7;if(top+height>window.innerHeight-10)top=Math.max(10,rect.top-height-7);tip.style.left=left+'px';tip.style.top=top+'px';tip.querySelector('.route-explain-close').onclick=e=>{e.stopPropagation();hideRouteExplanation(true)};if(pinned&&document.activeElement===anchor)tip.querySelector('.route-explain-close')?.focus({preventScroll:true});}
function renderRouteOverview(){const el=document.getElementById('routeOverview');el.innerHTML=ROUTES.map(r=>{const x=routeMeta[r],n=routeNarrative(r);return `<article class="route-summary"><div style="color:${x.color}"><span class="route-pattern ${x.pattern}"></span><b>${r} · ${esc(tr(x.title))}</b></div><div class="muted">${esc(tr(x.core_reason))}</div><dl class="route-summary-detail"><div><dt>${u('bestFor')}</dt><dd>${esc(n.best_for)}</dd></div><div><dt>${u('tradeoff')}</dt><dd>${esc(n.tradeoff)}</dd></div><div><dt>${u('routeRule')}</dt><dd>${esc(n.decision_rule)}</dd></div></dl></article>`}).join('');}
function applyPanelSize({persist=false}={}){state.panelWidth=Math.max(300,Math.min(620,Number(state.panelWidth)||390));state.mobilePanelHeight=Math.max(30,Math.min(70,Number(state.mobilePanelHeight)||48));const app=document.getElementById('app');app.style.setProperty('--sidebar-width',state.panelWidth+'px');app.style.setProperty('--mobile-panel-height',state.mobilePanelHeight+'%');const splitter=document.getElementById('panelResizer');if(splitter)splitter.setAttribute('aria-valuenow',String(Math.round(state.panelWidth)));if(persist){try{localStorage.setItem('trip_panel_width',String(Math.round(state.panelWidth)));localStorage.setItem('trip_mobile_panel_height',String(Math.round(state.mobilePanelHeight)))}catch{}persistState()}requestAnimationFrame(()=>photoMap?.resize());}
function setPanelHidden(hidden){const app=document.getElementById('app'),toggle=document.getElementById('panelToggle');if(hidden&&!app.classList.contains('panel-hidden'))panelReturnFocus=document.activeElement;state.panelHidden=hidden;app.classList.toggle('panel-hidden',hidden);const sidebar=document.getElementById('sidebar');if(sidebar)sidebar.setAttribute('aria-hidden',String(hidden));renderControls();persistState();setTimeout(()=>{photoMap?.resize();if(hidden)document.getElementById('panelReopen')?.focus({preventScroll:true});else panelReturnFocus?.focus?.({preventScroll:true})},110);}
function adjustPanel(direction){if(isMobile())state.mobilePanelHeight+=direction*10;else state.panelWidth+=direction*60;applyPanelSize({persist:true});}
function renderControls(){
  document.documentElement.dataset.theme=state.theme;document.documentElement.lang=state.lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=u(el.dataset.i18n)});
  document.querySelectorAll('[data-route]').forEach(b=>{const x=routeMeta[b.dataset.route];b.classList.toggle('active',state.routes.has(b.dataset.route));b.setAttribute('aria-pressed',state.routes.has(b.dataset.route));b.style.setProperty('--route-color',x.color);b.title=`${b.dataset.route} · ${tr(x.title)} — ${tr(x.core_reason)}`});
  document.querySelectorAll('[data-route-info]').forEach(b=>{const r=b.dataset.routeInfo;b.style.setProperty('--route-color',routeMeta[r].color);b.setAttribute('aria-label',`${u('explainRoute')} ${r}`)});
  document.querySelectorAll('[data-region]').forEach(b=>{b.classList.toggle('active',state.region===b.dataset.region);b.setAttribute('aria-pressed',state.region===b.dataset.region)});
  document.querySelectorAll('[data-provider]').forEach(b=>b.classList.toggle('active',state.provider===b.dataset.provider));
  ['dateSelect','mobileDate'].forEach(id=>{const el=document.getElementById(id);if(el){el.value=state.date;for(const option of el.options)option.textContent=option.value==='all'?u('allDates'):dateLabel(option.value)}});
  const region=document.getElementById('mobileRegion');if(region){region.value=state.region;for(const option of region.options)option.textContent=u(option.value)}
  const provider=document.getElementById('mobileProvider');if(provider){provider.value=state.provider;for(const option of provider.options)option.textContent=u(option.value)}
  document.getElementById('themeToggle').textContent=state.theme==='dark'?'☀ '+u('lightTheme'):'☾ '+u('dark');
  document.getElementById('langToggle').textContent=state.lang==='ko'?'EN':'한국어';
  const panelHidden=document.getElementById('app').classList.contains('panel-hidden');document.getElementById('panelToggle').textContent=panelHidden?u('showPanel'):u('hidePanel');document.getElementById('panelToggle').setAttribute('aria-controls','sidebar');document.getElementById('panelToggle').setAttribute('aria-expanded',String(!panelHidden));document.getElementById('panelReopen').textContent=u('showPanel');document.getElementById('panelReopen').setAttribute('aria-expanded',String(!panelHidden));document.getElementById('panelSmaller').setAttribute('aria-label',u('smallerPanel'));document.getElementById('panelSmaller').title=u('smallerPanel');document.getElementById('panelLarger').setAttribute('aria-label',u('largerPanel'));document.getElementById('panelLarger').title=u('largerPanel');document.getElementById('panelClose').setAttribute('aria-label',u('hidePanel'));document.getElementById('panelClose').title=u('hidePanel');document.getElementById('panelResizer').setAttribute('aria-label',u('resizePanel'));
  document.getElementById('mapRouteLegend').innerHTML=ROUTES.map(r=>`<div class="map-route-row ${state.routes.has(r)?'active':'inactive'}" title="${esc(tr(routeMeta[r].title))}"><i style="background:${routeMeta[r].color}"></i><b>${esc(r)}</b><span>${esc(tr(routeMeta[r].title))}</span></div>`).join('');
  renderProviderState();document.getElementById('fieldSummaryText').textContent=u('fieldSummary');document.getElementById('branchLegendText').textContent=u('branchLegend');document.getElementById('activeFilterSummary').textContent=`${state.routes.size} ${u('routes').toLowerCase()} · ${state.date==='all'?u('allDates'):dateLabel(state.date)} · ${u(state.region)}`;const freshness=document.getElementById('freshnessNote');if(freshness)freshness.textContent=`${u('freshness')} · ${FRESHNESS.default_status||'RECHECK_REQUIRED'}`;const fallback=document.getElementById('fallbackNote');if(fallback){const failed=state.provider==='vector'&&[...state.providerEvents].reverse().some(e=>e.type==='fallback_to_smart');fallback.textContent=state.provider==='vector'?(failed?u('providerFailure'):u('providerReady')):`${u(state.provider)} · ${u('liveReady')}`;}
}
async function filtersChanged(){hidePreview();document.getElementById('routeTip').classList.remove('show');if(state.selected&&!markerVisible(markerByKey[state.selected]))state.selected=null;renderDetail(state.selected);renderTimeline();persistState();await drawMap(false);}
function setTab(t){state.tab=t;document.querySelectorAll('.tab').forEach(b=>{const a=b.dataset.tab===t;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a));b.setAttribute('tabindex',a?'0':'-1')});document.querySelectorAll('.pane').forEach(p=>{const active=p.id===(t==='timeline'?'timelinePane':'detailsPane');p.classList.toggle('active',active);p.hidden=!active});if(isMobile())renderMapFocus(state.selected);persistState();}
function bind(){
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{const r=b.dataset.route;if(state.routes.has(r)&&state.routes.size>1)state.routes.delete(r);else state.routes.add(r);await filtersChanged()});
  document.querySelectorAll('[data-route-info]').forEach(b=>{const r=b.dataset.routeInfo;b.onmouseenter=()=>showRouteExplanation(r,b);b.onmouseleave=()=>{routeExplainTimer=setTimeout(()=>hideRouteExplanation(),140)};b.onfocus=()=>{if(suppressRouteInfoFocus){suppressRouteInfoFocus=false;return}showRouteExplanation(r,b)};b.onblur=()=>{routeExplainTimer=setTimeout(()=>hideRouteExplanation(),140)};b.onclick=e=>{e.stopPropagation();if(routeExplainPinned===r)hideRouteExplanation(true);else showRouteExplanation(r,b,{pinned:true})}});
  const routeExplain=document.getElementById('routeExplain');routeExplain.onmouseenter=()=>clearTimeout(routeExplainTimer);routeExplain.onmouseleave=()=>{routeExplainTimer=setTimeout(()=>hideRouteExplanation(),180)};
  document.querySelectorAll('[data-region]').forEach(b=>b.onclick=async()=>{state.region=b.dataset.region;await filtersChanged()});
  document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>chooseProvider(b.dataset.provider));
  for(const id of ['dateSelect','mobileDate']){const e=document.getElementById(id);if(e)e.onchange=async()=>{state.date=e.value;await filtersChanged()}}
  const mr=document.getElementById('mobileRegion');if(mr)mr.onchange=async()=>{state.region=mr.value;await filtersChanged()};const mp=document.getElementById('mobileProvider');if(mp)mp.onchange=()=>chooseProvider(mp.value);
  document.querySelectorAll('.tab').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const tabs=[...document.querySelectorAll('.tab')],next=tabs[(tabs.indexOf(b)+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];setTab(next.dataset.tab);next.focus()}}});
  document.getElementById('themeToggle').onclick=async()=>{state.theme=state.theme==='dark'?'light':'dark';try{localStorage.setItem('trip_theme',state.theme)}catch{}persistState();hideRouteExplanation(true);await drawMap(true);renderTimeline();renderDetail(state.selected)};
  document.getElementById('langToggle').onclick=async()=>{state.lang=state.lang==='ko'?'en':'ko';try{localStorage.setItem('trip_lang',state.lang)}catch{}persistState();hideRouteExplanation(true);renderRouteOverview();renderTimeline();renderDetail(state.selected);await drawMap(true)};
  document.getElementById('panelToggle').onclick=()=>setPanelHidden(!document.getElementById('app').classList.contains('panel-hidden'));
  document.getElementById('panelClose').onclick=()=>setPanelHidden(true);document.getElementById('panelReopen').onclick=()=>setPanelHidden(false);document.getElementById('panelSmaller').onclick=()=>adjustPanel(-1);document.getElementById('panelLarger').onclick=()=>adjustPanel(1);
  const splitter=document.getElementById('panelResizer');let resizeStart=null;splitter.onpointerdown=e=>{if(isMobile())return;resizeStart={x:e.clientX,width:state.panelWidth};splitter.setPointerCapture(e.pointerId);splitter.classList.add('dragging');e.preventDefault()};splitter.onpointermove=e=>{if(!resizeStart)return;state.panelWidth=resizeStart.width+(resizeStart.x-e.clientX);applyPanelSize()};splitter.onpointerup=e=>{if(!resizeStart)return;resizeStart=null;splitter.releasePointerCapture(e.pointerId);splitter.classList.remove('dragging');applyPanelSize({persist:true})};splitter.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();adjustPanel(e.key==='ArrowLeft'?1:-1)}};
  const preview=document.getElementById('previewCard');preview.addEventListener('error',e=>{const img=e.target;if(img?.tagName==='IMG'&&!img.src.startsWith('data:'))showMapFailure(new Error(`Missing local photo ${img.getAttribute('src')||''}`),'photo_asset')},true);preview.onmouseenter=()=>clearTimeout(window.__previewTimer);preview.onmouseleave=()=>{if(!state.touch)hidePreview()};
  document.addEventListener('click',e=>{if(routeExplainPinned&&!e.target.closest('#routeExplain,[data-route-info]'))hideRouteExplanation(true)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const returnedFromPreview=document.getElementById('previewCard')?.classList.contains('show');if(returnedFromPreview)hidePreview({returnFocus:true});if(document.getElementById('mapFocus')?.classList.contains('show')){document.getElementById('mapFocus').classList.remove('show');document.getElementById('mapFocus').setAttribute('aria-hidden','true');mapFocusReturnTarget?.focus?.({preventScroll:true});mapFocusReturnTarget=null}if(document.getElementById('routeExplain')?.classList.contains('show')){if(returnedFromPreview){routeExplainPinned=null;routeExplainReturnTarget=null;clearTimeout(routeExplainTimer);document.getElementById('routeExplain').classList.remove('show');document.getElementById('routeExplain').setAttribute('aria-hidden','true');document.querySelectorAll('[data-route-info]').forEach(b=>b.setAttribute('aria-expanded','false'));}else hideRouteExplanation(true)}else{routeExplainPinned=null;routeExplainReturnTarget=null}if(document.activeElement===splitter)splitter.blur()}});
  window.addEventListener('resize',()=>{applyPanelSize();photoMap?.resize()});applyPanelSize();
}
function setLoading(stage){const el=document.getElementById('loadingStatus');if(el)el.textContent=stage;}
async function hideLoading(){const screen=document.getElementById('loadingScreen');if(!screen){state.loadingStatus='ready';return;}const elapsed=performance.now()-(window.__tripLoadStarted||0);if(elapsed<900)await new Promise(resolve=>setTimeout(resolve,900-elapsed));state.loadingStatus='ready';screen.classList.add('ready');screen.setAttribute('aria-hidden','true');setTimeout(()=>screen.remove(),100);}
function runtimeSnapshot(){return {provider:state.provider,provider_identity:state.providerIdentity,provider_health:{...state.providerHealth},app_ready:state.appReady,map_visual_ready:state.mapVisualReady,loading_status:state.loadingStatus,provider_events:state.providerEvents.slice(),local_assets:{status:state.localAssets.status,failures:state.localAssets.failures.slice(),pending:state.localAssets.pending,completed:state.localAssets.completed,failed:state.localAssets.failed,resources:state.localAssets.resources.slice(-20)},planning_state:{routes:[...state.routes].sort(),date:state.date,region:state.region,selected:state.selected,tab:state.tab,lang:state.lang,theme:state.theme,panel_hidden:state.panelHidden},runtime:{...state.runtime,events:state.runtime.events.slice()},provider_stats:JSON.parse(JSON.stringify(state.providerStats)),map:{canvas_count:document.querySelectorAll('.maplibregl-canvas').length,photo_markers:document.querySelectorAll('.photo-marker').length,photo_marker_keys:[...document.querySelectorAll('.photo-marker')].map(x=>x.dataset.placeKey),clusters:document.querySelectorAll('.photo-cluster').length,leg_markers:document.querySelectorAll('.route-leg-label').length,layers:photoMap?.getStyle?.()?.layers?.length||0,visual:mapVisualSnapshot()}};}
async function init(){window.__tripLoadStarted=window.__tripLoadStarted||performance.now();state.touch=('ontouchstart'in window)||navigator.maxTouchPoints>0;document.documentElement.dataset.theme=state.theme;window.__tripApp={state,DATA,drawMap,whenIdle:()=>drawQueue,map:()=>photoMap,whenMapVisualReady:()=>waitForMapVisualReady(photoMap).then(value=>{state.mapVisualReady=true;return value}),mapVisualSnapshot,setupVector,selectPlace,chooseProvider,testProvider,setTab,markerVisible,timelineVisible,legVisible,visibleRouteFeatures,renderTimeline,renderDetail,showPreview,hidePreview,fitVisibleMap,runtimeSnapshot};setLoading(state.lang==='ko'?'로컬 스마트 지도를 여는 중…':'Opening the local Smart map…');await setupVector();if(state.selected&&!markerByKey[state.selected])state.selected=null;setLoading(state.lang==='ko'?`${DATA.markers.length}개 장소와 ${ROUTES.length}개 경로를 연결하는 중…`:`Connecting ${DATA.markers.length} places across ${ROUTES.length} routes…`);renderRouteOverview();renderTimeline();renderDetail(state.selected);bind();if(state.panelHidden)setPanelHidden(true);setTab(state.tab);const drawn=await drawMap(false);if(!drawn)throw new Error('Smart map failed to render');setLoading(state.lang==='ko'?`${DATA.markers.length*3}장의 실제 사진 준비 완료`:`${DATA.markers.length*3} real photographs ready`);state.appReady=true;await hideLoading();}
window.addEventListener('DOMContentLoaded',()=>init().catch(error=>{console.error('Application initialization failed:',error);if(state.providerHealth.vector!=='failed')showMapFailure(error,'initialization');else setLoading(mapFailureText(error,'initialization'));document.getElementById('loadingScreen')?.classList.add('failed')}));
})();
