
(()=>{
const DATA=window.TRIP_DATA; const ROUTES=['A1','A2','B1','B2'];
const state={routes:new Set(ROUTES),provider:'offline',region:'overall',date:'all',selected:null,tab:'timeline',providerHealth:{offline:'ready'},touch:false};
const routeMeta=DATA.routes; const markerByKey=Object.fromEntries(DATA.markers.map(x=>[x.place_key,x]));
const isMobile=()=>window.matchMedia('(max-width:760px)').matches;
function routeIntersects(arr){return (arr||[]).some(r=>state.routes.has(r));}
function dateMatchesOccurrence(o){return state.date==='all'||(o.date||'').startsWith(state.date+' ' )||(o.date||'')===state.date;}
function markerVisible(m){if(!routeIntersects(m.routes))return false;if(state.region!=='overall'&&DATA.place_region[m.place_key]!==state.region)return false;if(state.date==='all')return true;return m.occurrences.some(o=>state.routes.has(o.route)&&dateMatchesOccurrence(o));}
function timelineVisible(t){if(!routeIntersects(t.routes))return false;if(state.date!=='all'&&t.date_key!==state.date)return false;if(state.region==='overall')return true;return t.regions.includes(state.region);}
function legVisible(l){if(!routeIntersects(l.routes))return false;if(state.date!=='all'&&l.date!==state.date)return false;if(state.region!=='overall'){
  const fr=DATA.place_region[l.from], tr=DATA.place_region[l.to]; if(fr!==state.region&&tr!==state.region)return false;
  if(l.render_style==='transfer_dots')return false;
}return true;}
function providerStyle(p){if(p==='offline')return 'white-bg';const t=DATA.providers[p].tile_template;return {version:8,sources:{base:{type:'raster',tiles:[t],tileSize:256}},layers:[{id:'base',type:'raster',source:'base'}]};}
function probeImage(url,timeout=2600){return new Promise(resolve=>{const img=new Image();let done=false;const end=v=>{if(done)return;done=true;clearTimeout(timer);img.onload=img.onerror=null;resolve(v)};const timer=setTimeout(()=>end(false),timeout);img.onload=()=>end(img.naturalWidth>0);img.onerror=()=>end(false);img.referrerPolicy='no-referrer';img.src=url+(url.includes('?')?'&':'?')+'health='+Date.now();});}
async function testProvider(p){if(p==='offline')return true;state.providerHealth[p]='loading';renderProviderState();const ok=await probeImage(DATA.providers[p].health_probe);state.providerHealth[p]=ok?'ready':'failed';renderProviderState();return ok;}
async function chooseProvider(p){if(p!=='offline'){const ok=await testProvider(p);if(!ok){state.provider='offline';document.getElementById('fallbackNote').textContent=`${DATA.providers[p].label} failed health check → clean offline fallback`;await drawMap(false);return;}}state.provider=p;document.getElementById('fallbackNote').textContent=p==='offline'?'Offline geographic fallback active; no external tile requests.':`${DATA.providers[p].label} ready after real tile probe.`;await drawMap(false);}
function renderProviderState(){const el=document.getElementById('providerState');el.textContent=Object.entries(state.providerHealth).map(([k,v])=>`${k}:${v}`).join(' · ');el.className='provider-state '+(state.providerHealth[state.provider]==='failed'?'failed':state.providerHealth[state.provider]==='ready'?'ready':'');document.querySelectorAll('[data-provider]').forEach(b=>{const p=b.dataset.provider;b.dataset.health=state.providerHealth[p]||'untested';b.title=(DATA.providers[p]?.label||p)+' · '+(state.providerHealth[p]||'untested');b.setAttribute('aria-pressed',state.provider===p);});}
function pointSeq(a,b,n=13){const pts=[];for(let i=0;i<n;i++){const t=i/(n-1);pts.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]);}return pts;}
function baseTraces(){const out=[];if(state.region==='overall'){for(const ring of DATA.offline_context.rings_latlon){out.push({type:'scattermap',lat:ring.map(x=>x[0]),lon:ring.map(x=>x[1]),mode:'lines',line:{color:'#98a2b3',width:1.4},hoverinfo:'skip',showlegend:false});}}const A=DATA.offline_context.region_anchors;out.push({type:'scattermap',lat:A.map(x=>x.lat),lon:A.map(x=>x.lon),mode:'markers',marker:{size:4,color:'#98a2b3'},customdata:A.map(x=>x.name),hovertemplate:'%{customdata}<extra></extra>',showlegend:false});return out;}
function legTraces(){const out=[];for(const l of DATA.legs){if(!legVisible(l))continue;const active=l.routes.filter(r=>state.routes.has(r));const common=l.routes.length===4;const color=common?'#344054':routeMeta[active[0]]?.color||'#667085';let n=l.render_style==='transfer_dots'?20:12;let pts=pointSeq(l.from_latlon,l.to_latlon,n);if(!common){const pat=routeMeta[active[0]]?.pattern; if(pat==='dash')pts=pts.filter((_,i)=>i%3!==1);if(pat==='dot')pts=pts.filter((_,i)=>i%2===0);if(pat==='dashdot')pts=pts.filter((_,i)=>i%4!==2);}out.push({type:'scattermap',lat:pts.map(x=>x[0]),lon:pts.map(x=>x[1]),mode:'markers',marker:{size:l.render_style==='transfer_dots'?3:(common?4.5:5.5),color,opacity:common?.64:.82},customdata:pts.map(()=>['LEG',l.label,l.mode,l.geometry_kind,active.join('/'),l.note]),hovertemplate:'<b>%{customdata[1]}</b><br>%{customdata[2]} · %{customdata[3]}<br>%{customdata[4]}<br><i>%{customdata[5]}</i><extra></extra>',showlegend:false});}return out;}
function markerTrace(){const m=DATA.markers.filter(markerVisible);return {type:'scattermap',lat:m.map(x=>x.lat),lon:m.map(x=>x.lon),mode:'markers',marker:{size:m.map(x=>state.selected===x.place_key?23:(x.is_common_all?12:16)),color:m.map(x=>state.selected===x.place_key?'#f79009':(x.is_common_all?'#101828':routeMeta[x.routes.find(r=>state.routes.has(r))]?.color||'#475467')),opacity:.96},customdata:m.map(x=>['STOP',x.place_key,x.title,x.cluster,x.routes.filter(r=>state.routes.has(r)).join('/'),x.why,x.photo_status]),hovertemplate:'<b>%{customdata[2]}</b><br>%{customdata[3]} · %{customdata[4]}<br>%{customdata[5]}<extra></extra>',showlegend:false};}
function visibleMarkerBounds(){const m=DATA.markers.filter(markerVisible);if(!m.length)return null;return {lat:[Math.min(...m.map(x=>x.lat)),Math.max(...m.map(x=>x.lat))],lon:[Math.min(...m.map(x=>x.lon)),Math.max(...m.map(x=>x.lon))]};}
async function drawMap(preserve=true){const traces=[...baseTraces(),...legTraces(),markerTrace()];const r=DATA.region_cfg[state.region];const layout={map:{style:providerStyle(state.provider),center:r.center,zoom:r.zoom},margin:{l:0,r:0,t:0,b:0},paper_bgcolor:'#e8edf3',plot_bgcolor:'#e8edf3',showlegend:false,uirevision:preserve?'trip-map':'reset'};Plotly.purge('map');await Plotly.newPlot('map',traces,layout,{responsive:true,displaylogo:false,scrollZoom:true,modeBarButtonsToRemove:['lasso2d','select2d','toImage']});const map=document.getElementById('map');map.removeAllListeners?.('plotly_click');map.removeAllListeners?.('plotly_hover');map.removeAllListeners?.('plotly_unhover');map.on('plotly_click',ev=>{const p=ev.points?.[0],d=p?.customdata;if(d&&d[0]==='STOP'){showPreview(d[1],p);selectPlace(d[1],{focus:false,openDetails:true});}});map.on('plotly_hover',ev=>{const p=ev.points?.[0],d=p?.customdata;if(d&&d[0]==='STOP')showPreview(d[1],p);});map.on('plotly_unhover',()=>{if(!state.touch)hidePreview();});renderControls();}
function preferredOccurrence(x){const occ=x.occurrences.filter(o=>state.routes.has(o.route)&&(state.date==='all'||dateMatchesOccurrence(o)));return occ[0]||x.occurrences.find(o=>state.routes.has(o.route))||x.occurrences[0];}
function showPreview(k,p){const x=markerByKey[k],o=preferredOccurrence(x),card=document.getElementById('previewCard');if(!x)return;card.innerHTML=`<div class="preview-media">REAL PHOTO PREVIEW SLOT<br>deferred with Phase 2</div><div class="preview-body"><div class="preview-title">${esc(x.title)}</div><div class="preview-meta">${esc(o?.date||'')} · ${esc(o?.time||'')} · ${esc(x.routes.filter(r=>state.routes.has(r)).join(' / '))}</div><div class="preview-why"><b>Why now?</b> ${esc(o?.reason||x.why)}</div></div>`;card.classList.add('show');const wrap=document.querySelector('.mapwrap').getBoundingClientRect();let left=(p?.event?.clientX||wrap.left+wrap.width*.52)-wrap.left+14,top=(p?.event?.clientY||wrap.top+wrap.height*.46)-wrap.top+14;const w=260,h=160;if(left+w>wrap.width)left=Math.max(8,left-w-28);if(top+h>wrap.height)top=Math.max(8,top-h-28);card.style.left=left+'px';card.style.top=top+'px';if(isMobile()){clearTimeout(window.__previewTimer);window.__previewTimer=setTimeout(hidePreview,2400);}}
function hidePreview(){document.getElementById('previewCard').classList.remove('show');}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function groupOccurrences(x){const groups={};for(const o of x.occurrences.filter(o=>state.routes.has(o.route)&&(state.date==='all'||dateMatchesOccurrence(o)))){const sig=[o.date,o.time,o.title,o.reason,o.advantage,o.status].join('|');if(!groups[sig])groups[sig]={...o,routes:[]};groups[sig].routes.push(o.route);}return Object.values(groups);}
function renderDetail(k){const x=markerByKey[k],panel=document.getElementById('detailsPane');if(!x){panel.innerHTML='<div class="empty">Select a map stop or timeline item.</div>';return;}const chips=x.routes.filter(r=>state.routes.has(r)).map(r=>`<span class="chip" style="background:${routeMeta[r].color}">${r}</span>`).join('');const occ=groupOccurrences(x);const photoRoles=['HERO','EXPERIENCE','SCALE / CONTEXT'];panel.innerHTML=`<h2>${esc(x.title)}</h2><div class="muted">${esc(x.cluster)} · independently verified ${x.lat.toFixed(5)}, ${x.lon.toFixed(5)}</div><div class="routechips">${chips}</div><div class="phase-note"><b>Phase 2 is frozen by instruction.</b> No remote images are requested. These are the exact three local-photo slots that will be populated when Phase 2 resumes.</div><div class="photo-grid">${photoRoles.map((r,i)=>`<div class="photo-slot" data-photo-role="${r}" data-photo-path="${i===0?x.photo_thumb:''}"><strong>${r}</strong><span>local real photo reserved</span></div>`).join('')}</div><div class="fact"><b>WHY THIS PLACE</b>${esc(x.why)}</div><div class="fact"><b>PLACE SUMMARY</b>${esc(x.summary)}</div><div class="fact"><b>ITINERARY TIMING — DEDUPED</b>${occ.length?occ.map(o=>`<div class="timeline-card no-map"><div class="tl-top"><div><div class="tl-title">${esc(o.title)}</div><div class="tl-time">${esc(o.date)} · ${esc(o.time||'—')}</div></div><span class="status-chip">${esc(o.status||'')}</span></div><div class="mini-routes">${o.routes.map(r=>`<span class="mini-route" style="background:${routeMeta[r].color}">${r}</span>`).join('')}</div><div class="tl-reason">${esc(o.reason)}</div><div class="adv">${esc(o.advantage||'')}</div></div>`).join(''):'<div class="muted">No timing in the current route/date filter.</div>'}</div>${x.decision_rules?.length?`<div class="fact"><b>DECISION / REPLAN RULES</b>${x.decision_rules.map(d=>`<div class="decision"><b>${esc(d.key)}</b><br>${esc(d.text)}</div>`).join('')}</div>`:''}<div class="fact"><a class="maps-link" href="${x.maps_url}" target="_blank" rel="noopener">Open Google Maps ↗</a></div>`;}
function focusPlace(k){const x=markerByKey[k];if(!x)return;const zoom=state.region==='overall'?10.8:Math.max(DATA.region_cfg[state.region].zoom,11.3);Plotly.relayout('map',{'map.center.lat':x.lat,'map.center.lon':x.lon,'map.zoom':zoom});}
function selectPlace(k,{focus=true,openDetails=true}={}){state.selected=k;renderDetail(k);renderTimeline();updateMarkerEmphasis();if(focus)focusPlace(k);if(openDetails)setTab('details');}
function updateMarkerEmphasis(){const div=document.getElementById('map');if(!div?.data?.length)return;const idx=div.data.findIndex(t=>t.customdata?.[0]?.[0]==='STOP');if(idx<0)return;const visible=DATA.markers.filter(markerVisible);Plotly.restyle(div,{'marker.size':[visible.map(x=>state.selected===x.place_key?23:(x.is_common_all?12:16))],'marker.color':[visible.map(x=>state.selected===x.place_key?'#f79009':(x.is_common_all?'#101828':routeMeta[x.routes.find(r=>state.routes.has(r))]?.color||'#475467'))]},[idx]);}
function routeMini(routes){return routes.filter(r=>state.routes.has(r)).map(r=>`<span class="mini-route" style="background:${routeMeta[r].color}">${r}</span>`).join('');}
function renderTimeline(){const pane=document.getElementById('timelinePane'),list=DATA.timeline.filter(timelineVisible);const grouped={};for(const t of list)(grouped[t.date]??=[]).push(t);let html=`<div class="timeline-tools"><div><b>Itinerary timeline</b><div class="timeline-count">${list.length} visible slots · map and timeline synchronized</div></div></div>`;for(const [date,arr] of Object.entries(grouped)){html+=`<section class="day"><div class="day-title">${esc(date)}</div>${arr.map(t=>{const mapped=t.spatial_keys.length>0;const selected=state.selected&&t.spatial_keys.includes(state.selected);return `<button class="timeline-card ${selected?'selected':''} ${mapped?'':'no-map'}" data-timeline="${t.id}" ${mapped?'':'disabled'}><div class="tl-top"><div class="tl-title">${esc(t.title)}</div><div class="tl-time">${esc(t.time||'—')}</div></div><div class="mini-routes">${routeMini(t.routes)}</div><div class="tl-reason">${esc(t.reason)}</div><div class="adv">${esc(t.advantage)}</div></button>`}).join('')}</section>`;}if(!list.length)html+='<div class="empty">No timeline slots match the current filters.</div>';pane.innerHTML=html;pane.querySelectorAll('[data-timeline]').forEach(b=>b.onclick=()=>{const t=DATA.timeline.find(x=>x.id===b.dataset.timeline);if(t?.spatial_keys?.length)selectPlace(t.spatial_keys[0],{focus:true,openDetails:false});});}
function renderRouteOverview(){const el=document.getElementById('routeOverview');el.innerHTML=ROUTES.map(r=>{const x=routeMeta[r];return `<div class="route-summary"><div style="color:${x.color}"><span class="route-pattern ${x.pattern}"></span><b>${r} · ${esc(x.title)}</b></div><div class="muted">${esc(x.core_reason)}</div></div>`}).join('');}
function renderControls(){document.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',state.routes.has(b.dataset.route));b.setAttribute('aria-pressed',state.routes.has(b.dataset.route));});document.querySelectorAll('[data-region]').forEach(b=>{b.classList.toggle('active',state.region===b.dataset.region);b.setAttribute('aria-pressed',state.region===b.dataset.region);});document.querySelectorAll('[data-provider]').forEach(b=>b.classList.toggle('active',state.provider===b.dataset.provider));['dateSelect','mobileDate'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=state.date});const mr=document.getElementById('mobileRegion');if(mr)mr.value=state.region;const mp=document.getElementById('mobileProvider');if(mp)mp.value=state.provider;renderProviderState();document.getElementById('activeFilterSummary').textContent=`${state.routes.size} route${state.routes.size===1?'':'s'} · ${state.date==='all'?'all dates':state.date} · ${DATA.region_cfg[state.region].label}`;}
async function filtersChanged(){if(state.selected&&!markerVisible(markerByKey[state.selected])){state.selected=null;renderDetail(null);}renderTimeline();await drawMap(false);}
function setTab(t){state.tab=t;document.querySelectorAll('.tab').forEach(b=>{const a=b.dataset.tab===t;b.classList.toggle('active',a);b.setAttribute('aria-selected',a)});document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('active',p.id===(t==='timeline'?'timelinePane':'detailsPane')));}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{const r=b.dataset.route;if(state.routes.has(r)&&state.routes.size>1)state.routes.delete(r);else state.routes.add(r);await filtersChanged();});document.querySelectorAll('[data-region]').forEach(b=>b.onclick=async()=>{state.region=b.dataset.region;await filtersChanged();});document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>chooseProvider(b.dataset.provider));for(const id of ['dateSelect','mobileDate']){const e=document.getElementById(id);if(e)e.onchange=async()=>{state.date=e.value;await filtersChanged();}}const mr=document.getElementById('mobileRegion');if(mr)mr.onchange=async()=>{state.region=mr.value;await filtersChanged();};const mp=document.getElementById('mobileProvider');if(mp)mp.onchange=()=>chooseProvider(mp.value);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));window.addEventListener('resize',()=>Plotly.Plots.resize('map'));}
async function init(){state.touch=('ontouchstart'in window)||navigator.maxTouchPoints>0;renderRouteOverview();renderTimeline();renderDetail(null);bind();setTab('timeline');await drawMap(false);window.__tripApp={state,DATA,drawMap,selectPlace,chooseProvider,testProvider,setTab,markerVisible,timelineVisible,legVisible,renderTimeline,renderDetail,showPreview,hidePreview};}
window.addEventListener('DOMContentLoaded',init);
})();
